open-cluster-management-io/ocm

solutions/deploy-a-helm-chart/README.md

The new version of clusteradm introduced a breaking change:
https://github.com/open-cluster-management-io/clusteradm/commit/263979dd9d0ec38f5ca30c6d87552b11a5e2326b
Signed-off-by: Tomer Figenblat <tfigenbl@redhat.com>

Fixed the install application-manager command

---

solutions/cluster-api/README.md
solutions/cluster-api/capi-join.sh
solutions/cluster-api/register-join.sh

Add cluster-api solution

---

controlplane/cmd/server/start.go
controlplane/hack/start-ocm-controlplane.sh
controlplane/pkg/apiserver/options/plugins.go
controlplane/pkg/apiserver/server.go

Enable admission and feature gate

---

solutions/deploy-argocd-apps/README.md
solutions/setup-dev-environment/README.md

I had trouble trying to follow this documentation because I couldn't complete the `./setup-ocm.sh` step. It took me a while to figure out the solution, hopefully this can help others who may run into the same issue.

Add to argocd documentation

---

test/integration/placement/assertion_test.go
test/integration/placement/placement_test.go

Fix: https://github.com/open-cluster-management-io/ocm/issues/162

stabilize placement integration test

---

.github/workflows/doc-only.yml

The GitHub docs about this issue: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks

Add: Empty Checkers when only having Doc changes.

---

pkg/registration/spoke/managedcluster/lease_controller_test.go

increase the waiting time for lease update test
- https://github.com/open-cluster-management-io/ocm/issues/173

:bug: increase waiting time for lease update test

---

test/integration/util/authentication.go
test/integration/util/recorder.go

add more debug info for autoapprove test for debugging test failure easily

:seedling: add more debug info for autoapprove test

---

.github/workflows/post.yml

We should upload coverage again after PR merged at the time of pushing a commit.
Otherwise, the base branch will keep missing like this: https://github.com/open-cluster-management-io/ocm/pull/163#issuecomment-1580267727
Reference: https://github.com/codecov/example-go/blob/c76b419d5641077a561ebf807ca1f403af5c0bd3/.github/workflows/ci.yml#L3

:bug: upload coverge again when push commit.

---

pkg/common/options/options.go
pkg/registration/spoke/spokeagent.go
pkg/registration/spoke/spokeagent_test.go
pkg/work/spoke/spokeagent.go

exposing the spoke informers to share them with other components which are integrated with registration agent in code level.

:seedling: expose the spoke informers

---

test/e2e-test.mk
test/e2e/common.go
test/e2e/e2e_suite_test.go

In some situations, the images used in the e2e-test are not with the same "image-tag". 
We should pass the image names of registration and work in the function `NewTester ` instead of the "image-tag".

:bug: Fix: hard-coded image names in e2e-test when create klusterlet.

---

Makefile
pkg/registration/helpers/testing/assertion.go
pkg/registration/helpers/testing/testinghelpers.go
pkg/registration/spoke/managedcluster/resource_reconcile.go
pkg/registration/spoke/managedcluster/resource_reconcile_test.go

rollback the merging the cluster capacity code
if the other component update the  cluster capacity, the registration agent will recover the changes

:bug:merge the cluster capacity

---

build/Dockerfile.placement
build/Dockerfile.registration
build/Dockerfile.registration-operator
build/Dockerfile.work
test/integration/registration/spokecluster_autoapproval_test.go

:bug: waiting the approved csr if it is not found in integration test

---

manifests/klusterlet/management/klusterlet-registration-deployment.yaml
manifests/klusterlet/management/klusterlet-work-deployment.yaml
pkg/operator/operators/klusterlet/controllers/bootstrapcontroller/bootstrapcontroller.go
pkg/operator/operators/klusterlet/controllers/bootstrapcontroller/bootstrapcontroller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/ssarcontroller/klusterlet_ssar_controller.go
pkg/operator/operators/klusterlet/controllers/ssarcontroller/klusterlet_ssar_controller_test.go
pkg/operator/operators/klusterlet/options.go

the klusterlet watches the secrets and deployments. when there are large numbers of secrets  or deployments in the managed cluster, the pod of klusterlet will be OOM because the cache size of secret/deployment informer is increased beyond the limit. So this PR is to filter the secret and deployment informer to reduce the case size.
Fixes #

:bug: filter secret informer to reduce cache size

---

pkg/common/apply/interface.go
pkg/common/apply/rbac.go
pkg/common/apply/rbac_test.go
pkg/common/patcher/patcher.go
pkg/registration/helpers/helpers.go
pkg/registration/helpers/helpers_test.go
pkg/registration/hub/addon/discovery_controller.go
pkg/registration/hub/addon/discovery_controller_test.go
pkg/registration/hub/clusterrole/controller.go
pkg/registration/hub/clusterrole/controller_test.go
pkg/registration/hub/clusterrole/manifests/managedcluster-registration-clusterrole.yaml
pkg/registration/hub/clusterrole/manifests/managedcluster-work-clusterrole.yaml
pkg/registration/hub/managedcluster/controller.go
pkg/registration/hub/managedcluster/controller_test.go
pkg/registration/hub/managedcluster/manifests/managedcluster-clusterrole.yaml
pkg/registration/hub/managedcluster/manifests/managedcluster-clusterrolebinding.yaml
pkg/registration/hub/managedcluster/manifests/managedcluster-namespace.yaml
pkg/registration/hub/managedcluster/manifests/managedcluster-registration-rolebinding.yaml
pkg/registration/hub/managedcluster/manifests/managedcluster-work-rolebinding.yaml
pkg/registration/hub/manager.go

This is to use lister for permission to avoid too frequent get calls. 
For all legacy k8s resource managed by registration, we add a cluster label and informer will use label selector to filter.
Fixes #

 🌱 Refactor cluster permission

---

pkg/work/spoke/spokeagent.go

Increase the default appliedmanifestwork eviction grace period from 10 minutes to 60 minutes
Fixes #

🌱 increase the default work eviction grace period to 60 minutes

---

.github/workflows/post.yml

https://github.com/open-cluster-management-io/clusteradm/pull/352

:sparkles: Trigger clusteradm e2e after post images.

---

.gitignore
pkg/registration/helpers/testing/testinghelpers.go
pkg/registration/hub/manager.go
pkg/registration/hub/rbacfinalizerdeletion/controller.go
pkg/registration/hub/rbacfinalizerdeletion/controller_test.go

when delete clustermanager cr, the registration-controller is deleted so fast to not remove the finalizer on work rolebinding in the cluster namespace. this PR is to refactor rbacfinalizercontroler to watch mcl and ns, remove the finalizer if there is no manifestworks when mcl or ns is deleting.
Fixes #

:bug: refactor rbacfinalizercontroller to fix cluster ns is terminating after delete clustermanager

---

pkg/cmd/spoke/operator.go
pkg/cmd/spoke/registration.go
pkg/cmd/spoke/work.go
pkg/placement/controllers/scheduling/schedule_test.go
pkg/work/spoke/statusfeedback/reader.go
pkg/work/spoke/statusfeedback/reader_test.go

This allows a jsonpatch to match multiple items and returns a list with jsonraw
Fixes #
https://github.com/open-cluster-management-io/work/issues/196

🐛 Being able to match multiple items in jsonpath

---

pkg/addon/OWNERS

add owner file for addon manager component
Fixes #

🌱 Add owner for addon manager component

---

go.mod
go.sum
pkg/addon/controllers/addontemplate/controller.go
pkg/addon/controllers/addontemplate/controller_test.go
pkg/addon/templateagent/template_agent.go
test/e2e/addonmanagement_test.go
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/controller.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/healthcheck_sync.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/utils.go
vendor/open-cluster-management.io/addon-framework/pkg/agent/inteface.go
vendor/open-cluster-management.io/addon-framework/pkg/utils/probe_helper.go

:seedling: use DeploymentAvailability to check addon health

---

test/e2e/addon_lease_test.go
test/e2e/addon_test.go
test/e2e/addonmanagement_test.go
test/e2e/e2e_suite_test.go
test/e2e/managedcluster_loopback_test.go
test/e2e/manifestworkreplicaset_test.go
test/e2e/work_webhook_test.go
test/e2e/work_workload_test.go

for work and addon e2e, we do not need to
restart klusterlet for each case
Fixes #

🌱 Reduce e2e process time

---

pkg/placement/controllers/scheduling/schedule.go
pkg/placement/controllers/scheduling/schedule_test.go
pkg/placement/controllers/scheduling/scheduling_controller.go
pkg/placement/controllers/scheduling/scheduling_controller_test.go
pkg/placement/debugger/debugger_test.go
pkg/placement/helpers/testing/builders.go
test/integration/placement/assertion_test.go
test/integration/placement/placement_test.go
test/integration/placement/prioritizer_test.go
test/integration/placement/toleration_test.go

🌱 placement support decision groups

---

.github/workflows/stable.yaml

This action can help us manage out-of-date issues. The official doc: https://github.com/actions/stale
`stable` label will be added to issues and PRs that have been inactive for **60** days
Close stale issues and PRs after **7** days of inactivity

:sparkles: Add stale check for issues and PRs.

---

.github/workflows/stable.yaml

Update the stable messages to be more reasonable.

:seedling: Update stable message and durations.

---

go.mod
go.sum
pkg/operator/helpers/helpers_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
test/e2e/addonmanagement_test.go
test/e2e/work_webhook_test.go
test/integration/operator/clustermanager_hosted_test.go
test/integration/operator/clustermanager_test.go
test/integration/operator/klusterlet_test.go
test/integration/registration/addon_lease_test.go
test/integration/registration/addon_registration_test.go
test/integration/registration/disaster_recovery_test.go
vendor/modules.txt
vendor/open-cluster-management.io/api/feature/feature.go

Enable the addon management feature gate by default for:
- clusterManager, will install the addon-manager component, if you want disable:
```yaml
apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
name: cluster-manager
spec:
...
addOnManagerConfiguration:
featureGates:
- feature: AddonManagement
mode: Disable
```
- klusterlet, will enable the addon management feature for the registration-agent, if you want to disable:
```yaml
apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
name: klusterlet
spec:
...
registrationConfiguration:
featureGates:
- feature: AddonManagement
mode: Disable
```
Fixes #

:warning: enable addon management feature gate by default

---

deploy/cluster-manager/config/rbac/cluster_role.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/manifests/cluster-manager.clusterserviceversion.yaml
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller_test.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_runtime_reconcile.go
test/integration/operator/clustermanager_hosted_test.go
test/integration/operator/clustermanager_test.go
test/integration/operator/integration_suite_test.go

1. Fix issue for cluster manger in hosted mode:
```
apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
name: cluster-manager
spec:
addOnManagerImagePullSpec: quay.io/open-cluster-management/addon-manager:latest
deployOption:
hosted:
registrationWebhookConfiguration:
address: management-control-plane
port: 30443
workWebhookConfiguration:
address: management-control-plane
port: 31443
mode: Hosted
placementImagePullSpec: quay.io/open-cluster-management/placement:latest
registrationImagePullSpec: quay.io/open-cluster-management/registration:latest
workImagePullSpec: quay.io/open-cluster-management/work:latest
status:
conditions:
- lastTransitionTime: "2023-07-14T07:51:04Z"
message: 'Failed to sync service account: serviceaccounts "work-controller-sa"
not found' …
```

:bug: Failed to sync sa work-controller-sa in cluster manger hosted mode

---

pkg/placement/controllers/scheduling/scheduling_controller.go

Fixes https://github.com/open-cluster-management-io/ocm/issues/233

:bug: fix the placement decision clusters have random order issue

---

deploy/klusterlet/config/crds/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/operator.open-cluster-management.io_klusterlets.yaml
go.mod
go.sum
manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml
pkg/common/helpers/annotations.go
pkg/common/helpers/annotations_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/registration/spoke/options.go
pkg/registration/spoke/registration/creating_controller.go
pkg/registration/spoke/registration/creating_controller_test.go
pkg/registration/spoke/spokeagent.go
test/integration/operator/klusterlet_test.go
test/integration/registration/clusterannotations_test.go
vendor/modules.txt
vendor/open-cluster-management.io/api/crdsv1beta1/0001_00_operator.open-cluster-management.io_klusterlets.crd.yaml
vendor/open-cluster-management.io/api/operator/v1/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml
vendor/open-cluster-management.io/api/operator/v1/types.go
vendor/open-cluster-management.io/api/operator/v1/zz_generated.deepcopy.go
vendor/open-cluster-management.io/api/operator/v1/zz_generated.swagger_doc_generated.go

The feature supports us to assign the annotations**(must have "agent.open-cluster-management.io" as prefix)** when creating a managed cluster from the agent side.
https://github.com/open-cluster-management-io/api/pull/252

:sparkles: Add ClusterAnnotations support.

---

pkg/work/spoke/controllers/manifestcontroller/manifestwork_controller.go

Ignore the manifest uid to avoid UID precondition failed error
Fixes #

:seedling: ignore the manifest uid

---

go.mod
go.sum
pkg/addon/controllers/addontemplate/controller.go
pkg/addon/manager.go
pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/values.go
pkg/addon/templateagent/values_test.go
test/e2e-test.mk
test/e2e/addonmanagement_test.go
test/integration/registration/spokeagent_restart_test.go
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/addondeploymentconfig.go
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/addonfactory.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/controller.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/manager.go
vendor/open-cluster-management.io/addon-framework/pkg/agent/inteface.go
vendor/open-cluster-management.io/addon-framework/pkg/index/index.go
vendor/open-cluster-management.io/addon-framework/pkg/utils/helpers.go
vendor/open-cluster-management.io/api/cluster/v1/types.go

Make the addon manger support override addon agents' images by the cluster's annotation.
If the managedCluster has annotation `open-cluster-management.io/image-registries` in format:
```
{
"registries":[
{
"mirror":"quay.io/ocm/addon-examples",
"source":"quay.io/open-cluster-management/addon-examples"
}
]
}
```
For example:
```
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
annotations:
open-cluster-management.io/image-registries: '{"registries":[{"mirror":"quay.io/ocm/addon-examples","source":"quay.io/open-cluster-management/addon-examples"}]}'
```
The addon-manager will override agent images for all the template-type addons whose images can match the `source` field.
Fixes #

:sparkles: Support override addon images by the cluster's annotation

---

pkg/operator/helpers/helpers.go
pkg/operator/operators/klusterlet/controllers/bootstrapcontroller/bootstrapcontroller.go
pkg/operator/operators/klusterlet/controllers/bootstrapcontroller/bootstrapcontroller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_runtime_reconcile.go
pkg/operator/operators/klusterlet/options.go
test/integration/operator/klusterlet_test.go

🐛 fix the rebootstrap issue

---

pkg/work/spoke/controllers/appliedmanifestcontroller/appliedmanifestwork_controller.go
pkg/work/spoke/controllers/appliedmanifestcontroller/appliedmanifestwork_controller_test.go

In a case where a managed cluster switches to a new hub with the same hub hash, the same manifestworks will be created for this cluster on the new hub without any condition. Once the work agent connects to the new hub, the applied resources of those manifestwork on this managed cluster should not be removed before the manifestworks are applied the first time.
Fixes #

🐛 skip sync of appliedmanifestwork if work is not applied yet

---

pkg/registration/webhook/start.go
pkg/work/webhook/start.go

Some cluster with old Kubernetes version may not support TLS 1.3 yet.
Fixes #

🐛 set tls min version to 1.2

---

deploy/klusterlet/config/rbac/cluster_role.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/klusterlet.clusterserviceversion.yaml
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/client_builder.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_managed_reconcile.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_management_recocile.go

🐛 add wlp annotation if necessary

---

Makefile
deploy/cluster-manager/PROJECT
deploy/cluster-manager/config/operator/operator.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/manifests/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/manifests/operator.open-cluster-management.io_clustermanagers.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/metadata/annotations.yaml
deploy/klusterlet/PROJECT
deploy/klusterlet/config/operator/operator.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/operator.open-cluster-management.io_klusterlets.yaml
deploy/klusterlet/olm-catalog/klusterlet/metadata/annotations.yaml
manifests/cluster-manager/management/cluster-manager-addon-manager-deployment.yaml
manifests/cluster-manager/management/cluster-manager-manifestworkreplicaset-deployment.yaml
manifests/cluster-manager/management/cluster-manager-placement-deployment.yaml
manifests/cluster-manager/management/cluster-manager-registration-deployment.yaml
manifests/cluster-manager/management/cluster-manager-registration-webhook-deployment.yaml
manifests/cluster-manager/management/cluster-manager-work-webhook-deployment.yaml
manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml
manifests/klusterlet/management/klusterlet-work-deployment.yaml

Fixes #
fix the securityContext warning when apply deployments.
```
Warning: would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "klusterlet" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "klusterlet" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "klusterlet" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "klusterlet" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

:bug:Fix PodSecurity Warnings

---

cmd/registration/main.go
cmd/work/main.go
pkg/addon/manager.go
pkg/cmd/webhook/registration.go
pkg/cmd/webhook/work.go
pkg/common/options/options.go
pkg/features/feature.go
pkg/placement/controllers/manager.go
pkg/registration/hub/manager.go
pkg/registration/webhook/v1/managedcluster_mutating.go
pkg/registration/webhook/v1/managedcluster_mutating_test.go
pkg/work/hub/manager.go
pkg/work/webhook/v1/manifestwork_validating.go
pkg/work/webhook/v1/manifestwork_validating_test.go
test/integration/registration/integration_suite_test.go

 🌱 Refactor code to start managers with shared informers

---

Makefile
deploy/cluster-manager/PROJECT
deploy/cluster-manager/config/operator/operator.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/manifests/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/manifests/operator.open-cluster-management.io_clustermanagers.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/metadata/annotations.yaml
deploy/klusterlet/PROJECT
deploy/klusterlet/config/operator/operator.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/operator.open-cluster-management.io_klusterlets.yaml
deploy/klusterlet/olm-catalog/klusterlet/metadata/annotations.yaml
manifests/cluster-manager/management/cluster-manager-addon-manager-deployment.yaml
manifests/cluster-manager/management/cluster-manager-manifestworkreplicaset-deployment.yaml
manifests/cluster-manager/management/cluster-manager-placement-deployment.yaml
manifests/cluster-manager/management/cluster-manager-registration-deployment.yaml
manifests/cluster-manager/management/cluster-manager-registration-webhook-deployment.yaml
manifests/cluster-manager/management/cluster-manager-work-webhook-deployment.yaml
manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml
manifests/klusterlet/management/klusterlet-work-deployment.yaml

This reverts commit ecc541d186dbf80a35c9cee68762aa7f17791e19.
Fixes #

:bug:  Revert "Fix PodSecurity Warnings"

---

pkg/placement/controllers/scheduling/schedule_test.go
pkg/placement/controllers/scheduling/scheduling_controller.go
pkg/placement/controllers/scheduling/scheduling_controller_test.go
pkg/placement/helpers/testing/builders.go
test/integration/placement/placement_test.go

:bug: revert placement decision start index from 1 to keep backward compatibility

---

pkg/addon/controllers/addonconfiguration/addon_configuration_reconciler_test.go
pkg/addon/controllers/addonconfiguration/controller.go
pkg/addon/controllers/addonconfiguration/mgmt_addon_progressing_reconciler_test.go
pkg/addon/controllers/addonmanagement/addon_install_reconciler.go
pkg/addon/controllers/addonmanagement/controller.go
pkg/addon/controllers/addonowner/controller.go
pkg/addon/controllers/addonprogressing/controller.go
pkg/addon/controllers/addontemplate/controller.go
pkg/addon/controllers/managementaddoninstallprogression/controller.go
pkg/addon/templateagent/registration.go
pkg/addon/templateagent/registration_test.go
pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/template_agent_test.go
pkg/addon/templateagent/values.go
pkg/addon/templateagent/values_test.go

Adding contextual logging 
Fixes #191 
For More Info:
https://www.kubernetes.dev/blog/2022/05/25/contextual-logging/
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

:seedling: adding contextual logging in addon pkg

---

pkg/placement/controllers/manager.go
pkg/placement/controllers/scheduling/cluster_event_handler_test.go
pkg/placement/controllers/scheduling/enqueue.go
pkg/placement/controllers/scheduling/enqueue_test.go
pkg/placement/controllers/scheduling/schedule.go
pkg/placement/controllers/scheduling/scheduling_controller.go
pkg/placement/plugins/addon/addon.go
pkg/placement/plugins/tainttoleration/taint_toleration.go

Summary
Adding contextual logging
Related issue(s)
Fixes https://github.com/open-cluster-management-io/ocm/issues/191
For More Info:
https://www.kubernetes.dev/blog/2022/05/25/contextual-logging/
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

:seedling: adding contextual logging in placement component

---

pkg/operator/operators/klusterlet/controllers/bootstrapcontroller/bootstrapcontroller.go
pkg/operator/operators/klusterlet/controllers/bootstrapcontroller/bootstrapcontroller_test.go
pkg/registration/clientcert/certificate.go
pkg/registration/clientcert/certificate_test.go
pkg/registration/spoke/spokeagent.go
pkg/registration/spoke/spokeagent_test.go
test/integration/registration/addon_registration_test.go
test/integration/registration/integration_suite_test.go
test/integration/registration/spokecluster_joining_test.go
test/integration/util/authentication.go
test/integration/util/proxy.go

Allow user to configure proxy settings in bootstrap hub kubeconfig.
Fixes #

✨ support proxy between hub cluster and managed cluster

---

Makefile
hack/init.sh

Fixes https://github.com/open-cluster-management-io/ocm/pull/261 error

:bug: fix make verify error

---

.github/workflows/e2e.yml
manifests/klusterlet/management/klusterlet-agent-deployment.yaml
pkg/operator/helpers/helpers.go
pkg/operator/helpers/queuekey.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_hub_reconcile.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_runtime_reconcile.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/client_builder.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_managed_reconcile.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_management_recocile.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_runtime_reconcile.go
test/e2e-test.mk
test/e2e/common.go
test/e2e/klusterlet_hosted_test.go

✨ support singleton in hosted mode

---

Makefile
pkg/operator/helpers/helpers_test.go
pkg/operator/helpers/queuekey.go
pkg/operator/operators/klusterlet/controllers/statuscontroller/klusterlet_status_controller_test.go
pkg/registration/clientcert/certificate.go
pkg/registration/helpers/helpers_test.go
pkg/registration/webhook/v1/managedcluster_mutating.go
test/e2e/placement_test.go
test/integration/addon/assertion_test.go
test/integration/placement/assertion_test.go

:seedling: bump golangci-lint to v1.54.2

---

test/e2e-test.mk

Since the registration image string is a substring of the registration-operator image, it wasn't being updated correctly. Adding a trailing `$` to match the end of the line fixes this for me locally.
Fixes #

:bug: Match registration image exactly

---

manifests/klusterlet/managed/klusterlet-work-clusterrole-execution.yaml
manifests/klusterlet/managed/klusterlet-work-clusterrolebinding-execution.yaml
manifests/klusterlet/management/klusterlet-agent-deployment.yaml
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_managed_reconcile.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_runtime_reconcile.go
test/e2e/work_workload_test.go
test/integration/operator/klusterlet_singleton_test.go

🐛 Fix: change singleton agent sa to work sa

---

.github/workflows/release.yml
.github/workflows/releaseimage.yml
deploy/cluster-manager/config/operator/operator.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/manifests/cluster-manager.clusterserviceversion.yaml
deploy/klusterlet/config/operator/operator.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/operator.open-cluster-management.io_klusterlets.yaml
hack/changelog.py

🌱 Add release action

---

manifests/klusterlet/managed/klusterlet-work-clusterrolebinding-aggregate.yaml
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_managed_reconcile.go

the roleRef is changed in work-execution clusterrolebinding, so failed to update the clusterrolebinding during upgrade scenario. 
Fixes #

:bug:  fix failed update roleRef in clusterrolebinding in upgrade case

---

Makefile
deploy/cluster-manager/config/manifests/bases/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/0.12.0/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/0.12.0/operator.open-cluster-management.io_clustermanagers.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/cluster-manager.package.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/metadata/annotations.yaml
deploy/klusterlet/config/manifests/bases/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/klusterlet/0.12.0/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/klusterlet/0.12.0/operator.open-cluster-management.io_klusterlets.yaml
deploy/klusterlet/olm-catalog/klusterlet/klusterlet.package.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/klusterlet/metadata/annotations.yaml
test/olm-test.mk

:seedling: bump csv to 0.13.0

---

README.md

Add artifact hub badges:
https://artifacthub.io/packages/olm/community-operators/cluster-manager
https://artifacthub.io/packages/olm/community-operators/klusterlet
https://github.com/open-cluster-management-io/ocm/issues/296
Fixes #

:book: Add artifact hub badges

---

pkg/common/testing/assertion.go
pkg/work/helper/helpers.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_controller.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_controllers_test.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_deploy_reconcile.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_deploy_test.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_finalizer_test.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_index_test.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_status_reconcile.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_status_test.go
pkg/work/hub/test/helper.go
test/e2e/manifestworkreplicaset_test.go
test/integration/work/manifestworkreplicaset_test.go

✨ Implement ManifestWorkReplicaSet RollOut strategy 

---

Makefile

operator-sdk support Mac M2 locally build
$ ./_output/tools/bin/operator-sdk
bash: ./_output/tools/bin/operator-sdk: cannot execute binary file: Exec format error
Fixes #

:sparkles: operator sdk support arm64

---

deploy/cluster-manager/olm-catalog/cluster-manager/manifests/cluster-manager.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/klusterlet.clusterserviceversion.yaml
manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml
manifests/klusterlet/management/klusterlet-work-deployment.yaml

In our internal enviroment, pod PSP add security context `  readOnlyRootFilesystem: true`, this cause klusterlet container failed to start up due to this error 
`F1128 02:00:36.380318       1 cmd.go:161] mkdir /tmp/serving-cert-9`
believe this https://github.com/open-cluster-management-io/ocm/blob/2e7dba1e8980637bbd470bb10ee5a063f56dd338/vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go#L259-L267 code try to write something into /tmp dir
Fixes #

✨ klusterlet spec mount /tmp to emptydir volume

---

pkg/registration/helpers/testing/testinghelpers.go
pkg/work/helper/helpers.go
test/integration/util/assertion.go
test/integration/util/unstructured.go
test/integration/work/work_test.go

Fixes https://github.com/open-cluster-management-io/ocm/issues/323

🐛 skip namespace in resourceMeta for cluster scoped resource

---

pkg/registration/hub/lease/clocksynccontroller.go
pkg/registration/hub/lease/clocksynccontroller_test.go
pkg/registration/hub/manager.go
test/integration/registration/managedcluster_lease_test.go
test/integration/util/managedcluster.go

When hub and agent clock out of sync, the managed cluster status will show as 'Unknown' even the agent functions well.
Here we add a new condition to report clock out-of-sync, when we detect the clock of hub and a agent is not synced.
**The strategy:** 
Every time hub find the `renewTime` updated, we compare the `now` with `renewTime`. The 2 values should close to each other, if the `now` is faster than `renewTime` too much (over a lease duration), we will report clock out-of-sync.
depends on: https://github.com/open-cluster-management-io/api/pull/296
Fixes #

:sparkles:  Add a condition to report when hub and agent clock out of sync.

---

deploy/cluster-manager/config/operator/operator.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/manifests/cluster-manager.clusterserviceversion.yaml
deploy/klusterlet/config/operator/operator.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/klusterlet.clusterserviceversion.yaml
manifests/cluster-manager/management/cluster-manager-addon-manager-deployment.yaml
manifests/cluster-manager/management/cluster-manager-manifestworkreplicaset-deployment.yaml
manifests/cluster-manager/management/cluster-manager-placement-deployment.yaml
manifests/cluster-manager/management/cluster-manager-registration-deployment.yaml
manifests/cluster-manager/management/cluster-manager-registration-webhook-deployment.yaml
manifests/cluster-manager/management/cluster-manager-work-webhook-deployment.yaml
manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml
manifests/klusterlet/management/klusterlet-work-deployment.yaml

:seedling: update deployment securityContext

---

manifests/cluster-manager/test/cluster-manager-managedclustersetbindings-migration.yaml
manifests/cluster-manager/test/cluster-manager-managedclustersets-migration.yaml
pkg/operator/operators/clustermanager/controllers/migrationcontroller/migration_controller.go
pkg/operator/operators/clustermanager/controllers/migrationcontroller/migration_controller_test.go

1. Extract `parseStorageVersionMigrationFiles` and put it at the beginning of the reconcile.
1. motivation: the `removeStorageVersionMigrations` , `applyStorageVersionMigrations`, `syncStorageVersionMigrationsCondition` all have the parse files process, we should extract them into one place.
2. Move `supportStorageVersionMigration` before `removeStorageVersionMigrations` 
1. motivation: the `supported` is the base of every StorageVersionMigration related process, it should be done at the beginning. 
3. Change `applyStorageVersionMigrations` to `createStorageVersionMigrations` , add CRD check and remove the `update` part
1. motivation: If the current CRD storage version equals to the version base set in the storageversionmigration, then no need to create the svm instance, because if will …

:bug: migration-controller depending on cluster-manager condition.

---

pkg/addon/controllers/addonconfiguration/addon_configuration_reconciler.go
pkg/addon/controllers/addonconfiguration/controller.go
pkg/addon/controllers/addonconfiguration/graph.go
pkg/addon/controllers/addonconfiguration/mgmt_addon_progressing_reconciler.go
pkg/addon/controllers/addonconfiguration/mgmt_addon_progressing_reconciler_test.go
test/integration/addon/addon_manager_upgrade_test.go
test/integration/addon/assertion_test.go

:seedling:  addon support rollout configs

---

pkg/operator/operators/clustermanager/controllers/migrationcontroller/migration_controller.go
pkg/operator/operators/clustermanager/controllers/migrationcontroller/migration_controller_test.go

When create a StorageVersionMigration, using the cluster-manager as the ownerReference. When cluster-manager is removed, all Migrations will also be removed.
Previously, it uses a remove function that depending on:
https://github.com/open-cluster-management-io/ocm/blob/40135fd4baf762630ffc161b6341837081dc05c0/pkg/operator/operators/clustermanager/controllers/migrationcontroller/migration_controller.go#L52
From release to release the files list are changed, but during the upgrade the cluster-manager keep exisitng, so that old storageversionmigration CRs won't get removed ever.
Fixes #

:bug: Fix: using ownerRef to control the removal of storageversionmigrations.

---

test/e2e/e2e_suite_test.go
test/e2e/manifestworkreplicaset_test.go

Extend the timeout of manifestworkreplicaset e2e cases to aviod flake error, also add more log for debugging. 
Fixes #

:bug: Fix: move Enable ReplicaSet at the beginning and add more logs.

---

.github/workflows/post.yml
.github/workflows/pre.yml

Recently, the codecov push keeps fail, through test we know the token is not required for public repos, so we can remove the token to fix that failure, the approach is verified in cluster-proxy-addon repo: https://github.com/open-cluster-management-io/cluster-proxy/pull/174
Also the OCM_BOT_TOKEN also shows "Bad credentials" when we try to trigger clusteradmin e2e test after PR merged, can we have a check on that token in case it's out-of-date? @qiujian16 
Fixes #
https://github.com/open-cluster-management-io/ocm/actions/runs/7497318242/job/20410721816

:bug: Remove codecov token.

---

manifests/cluster-manager/management/cluster-manager-addon-manager-deployment.yaml
manifests/cluster-manager/management/cluster-manager-manifestworkreplicaset-deployment.yaml
manifests/cluster-manager/management/cluster-manager-placement-deployment.yaml
manifests/cluster-manager/management/cluster-manager-registration-deployment.yaml
manifests/cluster-manager/management/cluster-manager-registration-webhook-deployment.yaml
manifests/cluster-manager/management/cluster-manager-work-webhook-deployment.yaml
manifests/config.go
manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml
manifests/klusterlet/management/klusterlet-work-deployment.yaml
pkg/operator/helpers/helpers.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go

Configurable qos resources for containers managed by cluster-manager and klusterlet
Fixes #
https://github.com/open-cluster-management-io/api/pull/316

✨ Configurable qos resources for containers managed by cluster-manager and klusterlet

---

deploy/klusterlet/config/crds/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/operator.open-cluster-management.io_klusterlets.yaml
go.mod
go.sum
manifests/klusterlet/managed/klusterlet-work-clusterrole-execution.yaml
manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml
manifests/klusterlet/management/klusterlet-work-deployment.yaml
pkg/operator/helpers/helpers.go
pkg/operator/helpers/helpers_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
test/integration/operator/klusterlet_test.go
vendor/modules.txt
vendor/open-cluster-management.io/api/crdsv1beta1/0001_00_operator.open-cluster-management.io_klusterlets.crd.yaml
vendor/open-cluster-management.io/api/operator/v1/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml
vendor/open-cluster-management.io/api/operator/v1/types_klusterlet.go
vendor/open-cluster-management.io/api/operator/v1/zz_generated.swagger_doc_generated.go

✨ support configuration of the agent priorityclass

---

pkg/work/spoke/controllers/statuscontroller/availablestatus_controller.go
pkg/work/spoke/options.go
pkg/work/spoke/spokeagent.go
pkg/work/spoke/statusfeedback/reader.go
pkg/work/spoke/statusfeedback/reader_test.go

✨ Add a flag for work agent to set raw json length

---

test/e2e-test.mk

ref: https://issues.redhat.com/browse/ACM-10392
The default mode was set to `Singleton`, so the substitution command needs to also be updated to reflect the new default.
- #365

:bug: Fix mode replacement for hosted mode

---

pkg/registration/clientcert/certificate.go
pkg/registration/clientcert/certificate_test.go
test/integration/registration/spokecluster_autoapproval_test.go

Before: the CSR only be retriggerred when subject.CommonName doesn't match.
Now: if there is no certs match subject (commonnam + org + ou) , CSR get retriggered.

:sparkles: Retrigger CSR when certs doesn't has desired org and ou of subject(registrationConfig).

---

pkg/registration/clientcert/certificate.go
pkg/registration/clientcert/certificate_test.go

The commit edef33de92cd9af45709f24f8b35d4e4e96af822 introduced additional checks on the certificate subject. The issue is that the order of the groups and organizational units are not consistent, so it was causing the addon-framework to generate several CSRs with many coming back as invalid.
This takes the approach of sorting the strings before doing the comparison.

🐛 Fix the valid client certificate check

---

test/e2e/work_workload_test.go

In some e2e run, we got the fail msg:
```
I0318 15:04:17.916169   14492 common.go:823] manifestWork e2e-managedcluster-58mwkx/work-f4gvm : v1.ManifestWork{TypeMeta:v1.TypeMeta{Kind:"ManifestWork", APIVersion:"work.open-cluster-management.io/v1"}, ObjectMeta:v1.ObjectMeta{Name:"work-f4gvm", GenerateName:"", Namespace:"e2e-managedcluster-58mwkx", SelfLink:"", UID:"8d0f59e2-c7e7-4d14-b98a-f6b8b6e449ce", ResourceVersion:"22980", Generation:1, CreationTimestamp:time.Date(2024, time.March, 18, 15, 3, 17, 0, time.Local), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"created-for-testing":"true"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string{"cluster.open-cluster-management.io/manifest-work-cleanup"} …
```

:bug: Update EventuallyTimeout in work_workload_test.go

---

pkg/registration/hub/csr/controller_test.go
pkg/registration/hub/csr/reconciler.go
pkg/registration/hub/managedcluster/controller.go
pkg/registration/hub/managedcluster/controller_test.go
pkg/registration/hub/manager.go
test/integration/registration/clusterannotations_test.go
test/integration/registration/spokecluster_autoapproval_test.go

Remove the accept cluster logic from the CSR controller, and put them in the managed cluster controller  
Fixes #386

:bug: avoid cluster auto approve failed occasionally

---

.github/workflows/pre.yml

Codecov becomes because github api outage sometimes. Change to pass CI job when the codecov upload is failed.
https://github.com/codecov/codecov-action/issues/926

:bug: CI should pass when on codecov upload fail.

---

manifests/klusterlet/managed/klusterlet-work-clusterrole-execution.yaml

add permission to make work support to apply mutatingwebhookconfigurations and validatingwebhookconfigurations resouces.
https://github.com/open-cluster-management-io/ocm/issues/384
Fixes #

:bug: add admissionregistration group to work execution clusterrole

---

pkg/registration/spoke/lease/lease_controller.go
pkg/registration/spoke/lease/lease_controller_test.go

Nothing change in the real code, all changes is about u-t test cases.
We want to avoid using specific times like:
```go
// wait one cycle (1 ~ 1.25s)
time.Sleep(2000 * time.Millisecond)
```
or:
```go
// wait a few milliseconds to start the lease update routine
time.Sleep(500 * time.Millisecond)
```
When u-t is running on a different environment, it may cause inaccurate results.

:seedling: Refactor Lease controller test cases.

---

pkg/work/spoke/options.go

:bug: Add default values for workloadsourcedriver and worksourceloadconfig.

---

pkg/addon/controllers/addontemplate/controller.go
pkg/addon/templateagent/decorator.go
pkg/addon/templateagent/decorator_test.go
pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/template_agent_test.go
pkg/addon/templateagent/values.go
pkg/addon/templateagent/values_test.go
test/e2e/addonmanagement_test.go

✨ Set install namespace of addonTemplate from config

---

pkg/addon/templateagent/decorator.go
pkg/addon/templateagent/decorator_test.go

🐛  Set name of namespace in namespace decorator

---

deploy/cluster-manager/config/rbac/cluster_role.yaml
deploy/cluster-manager/olm-catalog/latest/manifests/cluster-manager.clusterserviceversion.yaml
deploy/klusterlet/config/crds/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml
deploy/klusterlet/olm-catalog/latest/manifests/operator.open-cluster-management.io_klusterlets.yaml
go.mod
go.sum
manifests/cluster-manager/management/cluster-manager-manifestworkreplicaset-deployment.yaml
manifests/config.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller_test.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_secret_reconcile.go
pkg/operator/operators/clustermanager/options.go
pkg/work/hub/options.go
test/integration/operator/clustermanager_hosted_test.go
test/integration/operator/clustermanager_test.go
test/integration/operator/integration_suite_test.go
vendor/modules.txt
vendor/open-cluster-management.io/api/crdsv1beta1/0001_00_operator.open-cluster-management.io_klusterlets.crd.yaml
vendor/open-cluster-management.io/api/feature/feature.go
vendor/open-cluster-management.io/api/operator/v1/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml
vendor/open-cluster-management.io/api/operator/v1/types_klusterlet.go
vendor/open-cluster-management.io/api/operator/v1/zz_generated.swagger_doc_generated.go

This PR adds the capability to configure the work driver for the work controller via the cluster manager.
https://issues.redhat.com/browse/ACM-10422

✨ support work driver config for cluster manager.

---

deploy/cluster-manager/config/rbac/cluster_role.yaml
deploy/cluster-manager/olm-catalog/latest/manifests/cluster-manager.clusterserviceversion.yaml
manifests/cluster-manager/management/cluster-manager-addon-manager-deployment.yaml
manifests/cluster-manager/management/cluster-manager-manifestworkreplicaset-deployment.yaml
manifests/cluster-manager/management/cluster-manager-placement-deployment.yaml
manifests/cluster-manager/management/cluster-manager-registration-deployment.yaml
manifests/cluster-manager/management/cluster-manager-registration-webhook-deployment.yaml
manifests/cluster-manager/management/cluster-manager-work-webhook-deployment.yaml
manifests/config.go
pkg/operator/helpers/helpers.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller_test.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_hub_reconcile.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_secret_reconcile.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_managed_reconcile.go

Support to sync the imagePullSecret `open-cluster-management-image-pull-credentials` in the operator ns to the hub namespace. 
Fixes #

:sparkles: Add image pullSecret to hub controllers

---

pkg/operator/operators/klusterlet/controllers/klusterletcontroller/client_builder.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_managed_reconcile.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_management_recocile.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_namespace_reconcile.go
test/e2e/klusterlet_test.go

🐛  Remove old ns when klusterlet ns is changed

---

pkg/common/helpers/event_recorder.go
pkg/common/helpers/event_recorder_test.go
pkg/placement/controllers/manager.go
pkg/registration/hub/lease/controller.go
pkg/registration/hub/lease/controller_test.go
pkg/registration/hub/manager.go
pkg/registration/hub/manifests/rbac/managedcluster-registration-clusterrole.yaml
pkg/registration/spoke/managedcluster/claim_reconcile_test.go
pkg/registration/spoke/managedcluster/joining_controller_test.go
pkg/registration/spoke/managedcluster/resource_reconcile_test.go
pkg/registration/spoke/managedcluster/status_controller.go
pkg/registration/spoke/spokeagent.go

✨ Send available condition events for managed cluster

---

pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_secret_reconcile.go

should not stop other reconcilers when failed to sync images.
Fixes #

:bug:  should not stop other reconcilers when failed to sync images

---

pkg/operator/helpers/helpers.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_managed_reconcile.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_namespace_reconcile.go
test/e2e/addonmanagement_test.go
test/e2e/klusterlet_test.go
test/integration/operator/klusterlet_hosted_test.go
test/integration/operator/klusterlet_singleton_test.go
test/integration/operator/klusterlet_test.go

The addon namespace should always be default on.
The operator will not create addon ns based
on klusterlet install namespace.
Fixes #

 🐛 Always create default addon namespace

---

pkg/operator/helpers/sa_syncer.go
pkg/operator/helpers/sa_syncer_test.go

🐛 Refresh external managed token secret if service account ns changes

---

pkg/addon/templateagent/decorator.go

Only decorate namespace for namespaced resources for template addons, otherwise if we set the `namespace` for cluster-scoped resources, and we want to use the annotation `addon.open-cluster-management.io/deletion-orphan` to orphan the resource when deleting the addon, the deleteOption will look like:
```
deleteOption:
propagationPolicy: SelectivelyOrphan
selectivelyOrphans:
orphaningRules:
- group: ""
name: open-cluster-management-agent-addon
namespace: open-cluster-management-agent-addon # added ns value
resource: namespaces
```
the extra `namespace` filed will result in the resource being deleted
Fixes #

🐛 Only decorate namespace for namespaced resources

---

pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller.go

:bug: igonre failed to get pullsecret error

---

pkg/addon/controllers/addonprogressing/controller.go
pkg/addon/controllers/addonprogressing/controller_test.go
pkg/registration/spoke/addon/configuration.go
pkg/registration/spoke/addon/configuration_test.go
pkg/registration/spoke/addon/lease_controller_test.go
pkg/registration/spoke/addon/registration_controller_test.go

🐛 Handle hosted mode addons in addon progressing controller

---

go.mod
go.sum
vendor/modules.txt
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/agentclient.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/baseclient.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/cert/cert_rotation.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/kafka/options.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/mqtt/options.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/optionsbuilder.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/sourceclient.go

Update sdk-go to support
-  Cert rotation for MQTT client
- Verify TLS with  host's ca set for MQTT client
Fixes #

:seedling: update sdk-go

---

pkg/common/options/options_test.go
pkg/registration/clientcert/certificate.go
pkg/registration/clientcert/certificate_test.go
pkg/registration/clientcert/controller_test.go
pkg/registration/helpers/testing/testinghelpers.go
pkg/registration/spoke/registration/secret_controller_test.go
pkg/registration/spoke/spokeagent.go
pkg/registration/spoke/spokeagent_test.go
test/integration/registration/spokeagent_restart_test.go
test/integration/util/authentication.go

🐛 Regenerate the hub kubeconfig secret if the cluster name of the current context changes

---

pkg/registration/clientcert/cert_controller.go

There are times when we do troubleshooting, find CSR is not triggered but no error msg in registration-agent pod logs.
It will be more friendly if we can have a event for this case.

:bug: Add event when stop creating CSR because of too many.

---

pkg/registration/webhook/start.go

🐛  Fix "log.SetLogger(...) was never called" in registration webhook

---

pkg/cmd/spoke/operator.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_managed_reconcile.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_namespace_reconcile.go
pkg/operator/operators/klusterlet/options.go

if the flag is set, default addon ns will not be created by the operator.
Fixes https://github.com/open-cluster-management-io/ocm/issues/474

✨ Add a disable-default-addon-namespace flag

---

pkg/addon/templateagent/registration.go
pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/template_agent_test.go
pkg/registration/spoke/managedcluster/status_controller.go

🐛 Check if template is nil when getting the addon agent registration namespace

---

.github/workflows/e2e.yml
pkg/operator/helpers/sa_syncer.go
pkg/operator/helpers/sa_syncer_test.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller.go
test/e2e/common.go

Compare the uid of the service account to check if the service account is recreated.
similar PR: https://github.com/open-cluster-management-io/ocm/pull/458
Fixes #https://github.com/open-cluster-management-io/ocm/issues/503

🐛 Refresh external managed token secret if service account is deleted

---

pkg/cmd/spoke/operator.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
pkg/operator/operators/klusterlet/options.go
test/integration/operator/klusterlet_test.go

in gitops case, klusterlet is deployed by ArgoCD, so klusterlet has a label [argocd.argoproj.io/instance=xxx](http://argocd.argoproj.io/instance=xxx). If everything created klusterlet inherits this label, these objects will be triggered as being managed by ArgoCD but actually they are not.
fix: to add a flag to enable sync labels feature, the default is disable.
Fixes #

:bug: add enable-sync-labels flag to klusterlet operator

---

go.mod
go.sum
manifests/cluster-manager/hub/0000_00_work.open-cluster-management.io_manifestworkreplicasets.crd.yaml
manifests/cluster-manager/hub/0000_00_work.open-cluster-management.io_manifestworks.crd.yaml
manifests/cluster-manager/hub/0000_03_addon.open-cluster-management.io_addontemplates.crd.yaml
pkg/work/spoke/apply/apply.go
pkg/work/spoke/apply/create_only_apply.go
pkg/work/spoke/apply/create_only_apply_test.go
pkg/work/spoke/apply/read_only_apply.go
pkg/work/spoke/apply/read_only_apply_test.go
pkg/work/spoke/apply/server_side_apply.go
pkg/work/spoke/controllers/manifestcontroller/manifestwork_controller.go
test/integration/work/updatestrategy_test.go
vendor/modules.txt
vendor/open-cluster-management.io/api/addon/v1alpha1/0000_03_addon.open-cluster-management.io_addontemplates.crd.yaml
vendor/open-cluster-management.io/api/work/v1/0000_00_work.open-cluster-management.io_manifestworks.crd.yaml
vendor/open-cluster-management.io/api/work/v1/types.go
vendor/open-cluster-management.io/api/work/v1/zz_generated.swagger_doc_generated.go
vendor/open-cluster-management.io/api/work/v1alpha1/0000_00_work.open-cluster-management.io_manifestworkreplicasets.crd.yaml

✨ Readonly strategy

---

pkg/registration/clientcert/cert_controller.go
test/integration/registration/addon_registration_test.go

Update ClusterCertificateRotated to false if the signer name is invalid, i.e:
```
- lastTransitionTime: "2024-06-07T08:11:10Z"
message: 'Failed to create CSR CertificateSigningRequest.certificates.k8s.io "addon-cluster1-hello-template-rlmsp"
is invalid: spec.signerName: Invalid value: "xxx-addon": must be a fully qualified
domain and path of the form ''example.com/signer-name'''
reason: ClientCertificateUpdateFailed
status: "False"
type: ClusterCertificateRotated
```
Fixes #https://github.com/open-cluster-management-io/ocm/issues/382

🐛 Update ClusterCertificateRotated to false if the signer name is invalid

---

pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_managed_reconcile.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_management_recocile.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_runtime_reconcile.go

:bug: fix issue that pull secret and ns are synced labels when enable-sync-labels is disabled

---

pkg/addon/controllers/addonprogressing/controller.go
test/integration/addon/addon_manager_upgrade_test.go

:bug:  update mca progressing condition when desired and last applied matches

---

pkg/work/spoke/statusfeedback/rules/rule.go
test/integration/cloudevents/statusfeedback_test.go
test/integration/util/unstructured.go
test/integration/work/statusfeedback_test.go

✨ Add well known status rule for daemonsets

---

.github/workflows/e2e.yml

Add an environment `USE_EXISTING_CLUSTER` for debugging e2e with act locally.
With this set true, we can create a kind cluster, and use `act -j e2e` to debug repeatedly, even if the test fails, the kind cluster will not be destroyed.
This will not affect the e2e running on the GitHub.
Fixes #

🌱 Debug e2e with an existing cluster

---

go.mod
go.sum
pkg/addon/templateagent/decorator.go
pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/template_agent_test.go
pkg/addon/templateagent/testmanifests/addontemplate.yaml
test/e2e/addonmanagement_test.go
test/e2e/manifests/addon/addon_template.yaml
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/addondeploymentconfig.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/controller.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/healthcheck_sync.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/utils.go
vendor/open-cluster-management.io/addon-framework/pkg/agent/inteface.go
vendor/open-cluster-management.io/addon-framework/pkg/utils/addon_config.go
vendor/open-cluster-management.io/addon-framework/pkg/utils/probe_helper.go

https://github.com/open-cluster-management-io/ocm/issues/368
Fixes #

✨ Support daemonSet with AddOnTemplate

---

test/e2e-test.mk

Except for the standard e2e prepare process: `test-e2e`.
We may also want to customized the process, for example:
```
make deploy-hub KUBECONFIG=/home/runner/.kube/hub1 HUB_KUBECONFIG=/home/runner/.kube/hub1-kubeconfig
make deploy-hub KUBECONFIG=/home/runner/.kube/hub2 HUB_KUBECONFIG=/home/runner/.kube/hub2-kubeconfig
make deploy-spoke-operator KUBECONFIG=/home/runner/.kube/spoke
run-e2e
```
The changes intend to make `deploy-hub` and `run-e2e` commands more independent, so we can reuse them in different e2e prepare processes.

:seedling:Refactor makefile e2e commands.

---

pkg/addon/templateagent/decorator.go
pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/template_agent_test.go
pkg/addon/templateagent/testmanifests/addontemplate_daemonset.yaml
pkg/addon/templateagent/testmanifests/addontemplate_deployment.yaml

Set the first daemonset namespace to the registration namespace if no deployments in the addonTemplate
Fixes #

🐛 Set the first daemonset namespace to registration namespace if no deployments

---

pkg/registration/spoke/bootstrapkubeconfigs.go

When I was debugging the registraiton issue, found this part of log is not shown. It turns out using the wrong FromContext function.

:bug: Fix: should use `klog.FromContext` instead of `log.FromContext`

---

manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/ssarcontroller/klusterlet_ssar_controller.go
test/integration/operator/klusterlet_mutiplehubs_test.go

The PR is to support MultiHubs also in the operator.
The PR is related to: https://github.com/open-cluster-management-io/ocm/pull/443

:sparkles:Operator support MultipleHubs.

---

hack/e2e_flaky_error_test.sh
hack/integration_flaky_error_test.sh

There are 2 scripts added:
Sometimes, we want to run integration/e2e test multiple times to reproduce the flaky error, this script allows you to run test many times util it's failed, then it collects then output  into` _output/flaky-error-test/` directory:
```sh
OCM git:(main) ✗ sh hack/integration_flaky_error_test.sh 10
Running test 1 of 2...
Test 1 passed
Running test 2 of 2...
...
Test 7 failed
Test 7 result stored in _output/flaky-error-test/integration_test_20240702-135926_7.output
```
---
Actually it tests out a integration and a e2e flaky error already:
```
[38;5;243m/Users/xuezhao/workspaces/OCM/test/integration/addon/addon_manager_upgrade_test.go:180[0m
[38;5;9m[FAILED] Failed after 3.010s.
Expected
<*errors.errorString | 0xc000fbfca0>: 
unexpected condition matches before …
```

:seedling: Add test scripts.

---

hack/e2e_flaky_error_test.sh
test/e2e/addonmanagement_test.go
test/e2e/manifests/addon/addon_template.yaml

Recently we got this addon-manager flaky errors very frequently:
```
[FAILED] Timed out after 300.000s.
Expected success, but got an error:
<*errors.errorString | 0xc000b835c0>: 
the addon e2e-universal-managedcluster-phbngt/hello-template available condition is not true, [{Progressing True 0 2024-07-05 04:47:53 +0000 UTC Progressing progressing... work is not ready} {RegistrationApplied True 0 2024-07-05 04:47:53 +0000 UTC SetPermissionApplied Registration of the addon agent is configured} {ClusterCertificateRotated False 0 2024-07-05 04:47:53 +0000 UTC ClientCertificateUpdateFailed Failed to rotated client certificate namespaces "open-cluster-management-agent-addon" not found} {ManifestApplied False 0 2024-07-05 04:47:53 +0000 UTC AddonManifestAppliedFailed failed to apply the manifests …
```

:bug: Fix: hello template e2e error.

---

test/integration/registration/spokecluster_autoapproval_test.go

Sometimes the update operation need another try.
To avoid errors like the following:
```
Event: [hub-managedclustercontroller] NamespaceCreated: Created Namespace/autoapprovaltest-spoke-cluster1 because it was missing 
[FAILED] in [It] - /home/runner/work/ocm/ocm/test/integration/registration/spokecluster_autoapproval_test.go:134 @ 07/05/24 03:36:20.343
• [FAILED] [0.011 seconds]
Cluster Auto Approval [It] Cluster can be denied by manually after automatically approved
/home/runner/work/ocm/ocm/test/integration/registration/spokecluster_autoapproval_test.go:100
[FAILED] Unexpected error:
<*errors.StatusError | 0xc0004cc500>: 
Operation cannot be fulfilled on managedclusters.cluster.open-cluster-management.io "autoapprovaltest-spoke-cluster1": the object has been modified; please apply your …
```

:bug: fix: put the update into a eventually to avoid flaky error.

---

hack/e2e_flaky_error_test.sh
test/e2e/addon_lease_test.go
test/e2e/addon_test.go
test/e2e/addonmanagement_test.go
test/e2e/common.go
test/e2e/e2e_suite_test.go
test/e2e/klusterlet_hosted_test.go
test/e2e/klusterlet_test.go
test/e2e/managedcluster_loopback_test.go
test/e2e/managedclustersetbinding_test.go
test/e2e/manifestworkreplicaset_test.go
test/e2e/placement_test.go
test/e2e/registration_taint_update_test.go
test/e2e/registration_webhook_test.go
test/e2e/work_workload_test.go

This PR first unified the way of using timeout and interval, currently we have 3 different ways of using them when writing a case:
1. From the Tester
https://github.com/open-cluster-management-io/ocm/blob/5617fec2f7345262966735a245b0a745bd558698/test/e2e/addon_lease_test.go#L205-L208
2. From the global varible and const
https://github.com/open-cluster-management-io/ocm/blob/5617fec2f7345262966735a245b0a745bd558698/test/e2e/work_workload_test.go#L33
https://github.com/open-cluster-management-io/ocm/blob/5617fec2f7345262966735a245b0a745bd558698/test/e2e/addonmanagement_test.go#L390-L392
3. From actual time
https://github.com/open-cluster-management-io/ocm/blob/5617fec2f7345262966735a245b0a745bd558698/test/e2e/managedclustersetbinding_test.go#L69-L71
In this PR, we will set the default …

:seedling: Refactor timeout and interval usage in e2e.

---

test/e2e-test.mk
test/e2e/addon_lease_test.go
test/e2e/addon_test.go
test/e2e/addonmanagement_test.go
test/e2e/e2e_suite_test.go
test/e2e/managedcluster_loopback_test.go
test/e2e/manifestworkreplicaset_test.go
test/e2e/work_webhook_test.go
test/e2e/work_workload_test.go

Cases are using a shared, universal klusterlet/managed cluster, rename the field to expilicitly hight this point.
Also:
* Remove the clusterName, klusterletName, agentNamespace from flags since they will always be named by: 
https://github.com/open-cluster-management-io/ocm/blob/b3f15c14f483884bb12fee7528321ef6e1d53608/test/e2e/e2e_suite_test.go#L85-L87
* Remove deploy-klusterlet from the flags since it's always true in our test.

:seedling: Explicitly rename and use universal klusterlet/managed cluster.

---

deploy/cluster-manager/olm-catalog/latest/manifests/cluster-manager.clusterserviceversion.yaml
deploy/klusterlet/config/manifests/bases/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/latest/manifests/klusterlet.clusterserviceversion.yaml

-------
Some minor typo fixes in the description that gets displayed in places
like the operator hub.
Fixes #

📖 Fix typos in ClusterServiceVersion description

---

pkg/operator/OWNERS

add dongbeiqing91 to operator approvers and reviewers
Fixes #

:seedling: add dongbeiqing91 to operator approvers and reviewers

---

pkg/operator/OWNERS

Add haowells to operator reviewers
Fixes #

🌱 Add haowells to operator reviewers

---

pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller.go

This PR will fix the bug that detaching cluster gets stuck when appliedManifestWork CRD does not exist on the hosted managed cluster
Fixes #

🐛 Ignore appliedmanifestwork crd not found error when checking managed cluster connectivity

---

pkg/operator/helpers/chart/render.go
pkg/operator/helpers/chart/render_test.go

update operator charts render function to return raw data of the results.
Fixes #

:seedling: return raw data of chart render results

---

deploy/cluster-manager/chart/config.go
deploy/klusterlet/chart/config.go
pkg/operator/helpers/chart/render.go
pkg/operator/helpers/chart/render_test.go

:seedling: add createNamespace option to chart render

---

Makefile
deploy/cluster-manager/chart/cluster-manager/templates/_helpers.tpl
deploy/cluster-manager/chart/cluster-manager/templates/cluster_manager.yaml
deploy/cluster-manager/chart/cluster-manager/values.yaml
deploy/cluster-manager/chart/config.go
deploy/klusterlet/chart/config.go
deploy/klusterlet/chart/klusterlet/templates/_helpers.tpl
deploy/klusterlet/chart/klusterlet/templates/klusterlet.yaml
deploy/klusterlet/chart/klusterlet/values.yaml
pkg/operator/helpers/chart/config.go
pkg/operator/helpers/chart/render.go
pkg/operator/helpers/chart/render_test.go
test/e2e-test.mk

1. support set imagepullsecret credential in the helm chart.
2. set the token-secret length to 16 in the chart.
3. use helm chart to deploy in e2e.
4. add a flag to control if create operator CR, because do not need create klusterlet CR in e2e deploy stage.  the default is to create. 
5. move the chart config struct to the helper dir. the consumer will only import the helper dir.
Fixes #

:seedling: support set imagepullsecret credential in helm chart and run e2e using helm chart

---

solutions/kueue-admission-check/README.md
solutions/kueue-admission-check/env/cp-c1.yaml
solutions/kueue-admission-check/env/cp-c2.yaml
solutions/kueue-admission-check/env/cp-c3.yaml
solutions/kueue-admission-check/env/msa-c1.yaml
solutions/kueue-admission-check/env/msa-c2.yaml
solutions/kueue-admission-check/env/msa-c3.yaml
solutions/kueue-admission-check/env/multicluster.x-k8s.io_clusterprofiles.yaml
solutions/kueue-admission-check/env/patch-clusterrole.json
solutions/kueue-admission-check/env/patch-mg-sa-cma.json
solutions/kueue-admission-check/env/placement.yaml
solutions/kueue-admission-check/env/single-clusterqueue-setup-mwrs.yaml
solutions/kueue-admission-check/job-demo1.yaml
solutions/kueue-admission-check/job-demo2.yaml
solutions/kueue-admission-check/multikueue-setup-demo1.yaml
solutions/kueue-admission-check/multikueue-setup-demo2.yaml
solutions/kueue-admission-check/placement-demo2-1.yaml
solutions/kueue-admission-check/placement-demo2-2.yaml
solutions/kueue-admission-check/setup-env.sh

- Add the document for setting up Multikueue environment using OCM Kueue Admission Check Controller.
- Add files for the environment set up.
- Document still needs refinement.
Update 25.08
- Fix docu.
REF: https://github.com/open-cluster-management-io/ocm/issues/369

🌱 OCM Kueue Admission Check Controller

---

go.mod

Revert golang version to 1.22.5 since [Cachito](https://github.com/containerbuildsystem/cachito/) doesn't support 1.22.6 yet.
Fixes #

:seedling: revert golang version to 1.22.5

---

pkg/work/spoke/apply/server_side_apply.go
pkg/work/spoke/apply/server_side_apply_test.go
test/integration/work/updatestrategy_test.go

Currently, if the required object has zero creationTime in metadata, it will cause kube-apiserver to increment generation even if nothing else changes when using SSA to apply work's manifests
https://github.com/kubernetes/kubernetes/issues/67610

:bug: remove the creationTimestamp from metadata when using SSA in work

---

pkg/work/spoke/statusfeedback/reader.go
pkg/work/spoke/statusfeedback/reader_test.go

This is to ensure the backward compatible when the feature gate is disabled
Fixes #

🐛 only read the first item when RawFeedbackJsonString is disabled

---

pkg/operator/operators/crdmanager/manager.go

Fix error message in PR https://github.com/open-cluster-management-io/registration-operator/pull/363
Fixes #

🌱 Fix error message

---

go.mod
go.sum
pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/template_agent_test.go
test/integration/addon/addon_manager_install_test.go
test/integration/addon/addon_manager_template_test.go
test/integration/addon/testmanifests/addontemplate.yaml
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/addonfactory.go
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/helm_agentaddon.go
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/template_agentaddon.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/controller.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/registration/controller.go
vendor/open-cluster-management.io/addon-framework/pkg/agent/inteface.go
vendor/open-cluster-management.io/addon-framework/pkg/utils/addon_config.go

:sparkles:  upgrade framework and check configured condition in addon template

---

pkg/addon/controllers/addonconfiguration/addon_configuration_reconciler_test.go
pkg/addon/controllers/addonconfiguration/graph.go

The issue is, when configuring configs in mca and cma (mca override part of cma configs), the mca has a chance to hang at progressing and hang at an empty spec hash . For example:
```
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
spec:
addOnMeta:
description: cluster-proxy
displayName: cluster-proxy
installStrategy:
placements:
- name: global
namespace: open-cluster-management-global-set
rolloutStrategy:
type: All
type: Placements
supportedConfigs: <== set managedproxyconfigurations and addondeploymentconfigs
- defaultConfig:
name: cluster-proxy
group: proxy.open-cluster-management.io
resource: managedproxyconfigurations
- defaultConfig:
name: deploy-config
namespace: config-namespace
group: addon.open-cluster-management.io
resource: …
```

:bug: fix the mca override cma configs issues

---

pkg/addon/controllers/addonconfiguration/controller.go
pkg/addon/controllers/addonmanagement/controller.go
pkg/addon/controllers/addontemplate/controller.go

Currently, there are [2 workers started for the addonConfigurationController](https://github.com/open-cluster-management-io/ocm/blob/33b409dae87e4b3854726e3d3cb5b2d7af95c166/pkg/addon/manager.go#L201), and this controller watches the ManagedClusterAddOn resource, when mca changes, it enqueues the managedClusterAddon [namespace and name](https://github.com/open-cluster-management-io/ocm/blob/33b409dae87e4b3854726e3d3cb5b2d7af95c166/pkg/addon/controllers/addonconfiguration/controller.go#L93) in the format "{namespace}/{name}", but in the sync func, it only [uses the name to get clusterManagementAddOn](https://github.com/open-cluster-management-io/ocm/blob/33b409dae87e4b3854726e3d3cb5b2d7af95c166/pkg/addon/controllers/addonconfiguration/controller.go#L105-L112).
Think about the case, there …

🐛 Ensure one cma is processed by one addon worker at the same time

---

solutions/deploy-argocd-apps-pull/README.md
solutions/deploy-argocd-apps-pull/getting-started.md
solutions/deploy-argocd-apps-pull/troubleshooting.md

Misc fixes and minor adjustments to the existing ArgoCD pull integration solution.
Fixes #

:book: doc: fix argocd pull solution not using the right context

---

deploy/cluster-manager/chart/cluster-manager/README.md
deploy/klusterlet/chart/klusterlet/README.md

https://github.com/open-cluster-management-io/ocm/issues/662
Fixes #

🌱 Fix typo in charts README

---

pkg/operator/operators/klusterlet/controllers/statuscontroller/klusterlet_status_controller.go

🐛 Fix duplicate deployment names in klusterlet-agent availability message

---

pkg/registration/hub/clusterrole/controller.go
pkg/registration/hub/gc/gc_cluster_rbac.go
pkg/registration/hub/managedcluster/controller.go
pkg/registration/hub/manifests/fs.go

Rename the clusterrole related files varibles to better reflect its usage. For the clusterrole that every mangaed cluster needs, use `CommonClusterRoleFiles`, and for the cluster specificed rbac files, we use `ClusterSpecificRbacFiles`.

:seedling:  Rename and relocate cluster related roles files.

---

pkg/registration/webhook/start.go
pkg/registration/webhook/v1beta2/webhook.go

We are not implementing any mutating or validating webhooks for `ManagedClusterSet` here, so we can remove this webhook registration section.

🌱  Remove ManagedClusterSet webhook registration part

---

pkg/registration/hub/managedcluster/controller.go
pkg/registration/hub/managedcluster/controller_test.go

This will fix the below problem
1. The hub has an accepted cluster.
2. Enable the auto approval feature
3. Set the cluster hubAcceptsClient to false
The cluster hubAcceptsClient should be able to set to false

:bug: Add auto approve annotation for an accepted cluster when auto approval enabled

---

pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_runtime_reconcile.go
pkg/operator/operators/klusterlet/controllers/ssarcontroller/klusterlet_ssar_controller.go

Before:
```
Message:		Failed to get cluster name from hub kubeconfig secret with error <nil>
```
After:
```
Message:		Failed to get cluster name from hub kubeconfig secret with error: the cluster name in the secret is empty
```

🐛 Fix issue with printing `<nil>` for error messages

---

pkg/registration/helpers/helpers.go
pkg/registration/hub/gc/gc_cluster_rbac.go
pkg/registration/hub/managedcluster/controller.go
pkg/registration/hub/managedcluster/controller_test.go
pkg/registration/hub/manifests/fs.go
pkg/registration/hub/manifests/rbac/managedcluster-clusterrole.yaml
test/integration/registration/managedcluster_accept_test.go

After set hubAcceptsClient to false, there are chances the rbac resources removed before the event is watched by the agent. If that happens, the change will never captured by the agent side.
So this change is to keep a `watch` role of managed cluster to let mangaed cluster watch events when it's not accepted.

:bug: Fix accetp false add rbac

---

CONTRIBUTING.md
manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
pkg/registration/helpers/helpers.go
pkg/registration/helpers/testing/testinghelpers.go
pkg/registration/register/aws_irsa/aws.go
pkg/registration/register/aws_irsa/aws_irsa.go
pkg/registration/register/aws_irsa/aws_irsa_test.go
pkg/registration/register/aws_irsa/aws_test.go
pkg/registration/spoke/options.go
pkg/registration/spoke/registration/registration.go
pkg/registration/spoke/spokeagent.go

The PR adds changes for  AWS IAM based authentication support for Open Cluster Management (OCM) for Amazon EKS clusters. This change updates the Klusterletconfig object by adding the registration driver for awsirsa when the value of registration-auth flag is set as awsirsa from clusteradm join command.
Fixes #

:sparkles: Add AWS IAM support

---

go.mod
go.sum
pkg/operator/helpers/helpers.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/registration/hub/manager_test.go
pkg/registration/webhook/v1/managedcluster_mutating_test.go
test/integration/operator/clustermanager_test.go
vendor/modules.txt
vendor/open-cluster-management.io/api/feature/feature.go

🌱 Update `api` dependency and remove unnecessary featureGate enabling part 

---

manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml
manifests/klusterlet/management/klusterlet-work-deployment.yaml
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
test/integration/operator/klusterlet_test.go

The leader election of the klusterlet-agent is disabled on the single node managed cluster to speed up the restart procedure. While it might cause that two pods with different configuration, such as images or bootstrap config, running at the same time. Some unexpected behavior happens in this situation, for example, when old and new agents both exist, they override hub-kubeconfig-secret with different value and trigger each other create csr constantly.
To fix those issues, it is necessary to enable the leader election of the klusterlet-agent on the single node managed cluster.
Fixes #

:seedling: enable leader election of klusterlet-agent on single node managed cluster

---

deploy/cluster-manager/olm-catalog/latest/manifests/cluster-manager.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/latest/manifests/klusterlet.clusterserviceversion.yaml
go.mod
go.sum
manifests/cluster-manager/hub/0000_00_work.open-cluster-management.io_manifestworkreplicasets.crd.yaml
manifests/cluster-manager/hub/0000_00_work.open-cluster-management.io_manifestworks.crd.yaml
manifests/cluster-manager/hub/0000_03_addon.open-cluster-management.io_addontemplates.crd.yaml
pkg/work/helper/helper_test.go
pkg/work/helper/helpers.go
pkg/work/spoke/controllers/manifestcontroller/manifestwork_reconciler.go
pkg/work/spoke/controllers/manifestcontroller/manifestwork_reconciler_test.go
pkg/work/spoke/controllers/statuscontroller/availablestatus_controller.go
pkg/work/spoke/controllers/statuscontroller/availablestatus_controller_test.go
test/integration/work/statusfeedback_test.go
test/integration/work/updatestrategy_test.go
vendor/modules.txt
vendor/open-cluster-management.io/api/addon/v1alpha1/0000_03_addon.open-cluster-management.io_addontemplates.crd.yaml
vendor/open-cluster-management.io/api/work/v1/0000_00_work.open-cluster-management.io_manifestworks.crd.yaml
vendor/open-cluster-management.io/api/work/v1/types.go
vendor/open-cluster-management.io/api/work/v1alpha1/0000_00_work.open-cluster-management.io_manifestworkreplicasets.crd.yaml

Support wildcard in the name and namespace of ManifestConfigs.ResourceIdentifier for feedbackRule and updateStrategy.
if the a resource matches more than 1 options, only the first one works.
https://github.com/open-cluster-management-io/ocm/issues/705
Fixes #

:sparkles: support wildcard in ManifestConfigs

---

pkg/addon/controllers/addonmanagement/controller.go

This is because in https://github.com/open-cluster-management-io/ocm/pull/654 we change the way to get key, but the missing part is the queuekey func for addon informers.
Fixes #

🐛 Should use metadata name queue key func for addon informer

---

manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml
manifests/klusterlet/management/klusterlet-work-deployment.yaml
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
pkg/registration/spoke/spokeagent.go
pkg/singleton/spoke/agent.go
test/integration/operator/klusterlet_test.go

The leader election of the klusterlet-agent is disabled on the single node managed cluster to speed up the restart procedure (https://github.com/open-cluster-management-io/registration-operator/pull/193). While it might cause that two pods with different configuration, such as images or bootstrap config, running at the same time. Some unexpected behavior happens in this situation, for example, when old and new agents both exist, they override hub-kubeconfig-secret with different value and trigger each other create csr constantly.
To fix those issues, it is necessary to enable the leader election of the klusterlet-agent on the single node managed cluster.
https://github.com/open-cluster-management-io/ocm/pull/695

:seedling: enable leader election of klusterlet-agent on single node managed clusters

---

go.mod
go.sum
manifests/cluster-manager/hub/cluster-manager-addon-manager-clusterrole.yaml
pkg/addon/controllers/addontemplate/controller.go
pkg/addon/manager.go
pkg/addon/templateagent/registration.go
pkg/addon/templateagent/registration_test.go
pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/template_agent_test.go
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/addonconfig/controller.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/controller.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/certificate/csrapprove.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/certificate/csrsign.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/registration/controller.go

🐛 Only bind the agent role for the addon group

---

.github/workflows/stale.yaml

- Fix the GitHub stale workflow to correctly state remove the `stale` label instead of the `stable` label.
- Renamed the file from stable to stale as well
An example of the `stable` usage: https://github.com/open-cluster-management-io/ocm/issues/514#issuecomment-2463603076

:seedling: Fix the GitHub stale workflow to correctly state remove the stale label

---

manifests/cluster-manager/hub/cluster-manager-addon-manager-clusterrole.yaml
pkg/addon/controllers/addontemplate/controller.go
pkg/addon/manager.go
pkg/addon/templateagent/registration.go
pkg/addon/templateagent/registration_test.go
pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/template_agent_test.go

* Only bind the agent role for the addon group
* Update addon rolebinding
* Start an addon informor for each addon
---------
Fixes #

🐛 [release-0.15] Only bind the agent role for the addon group

---

Makefile
build/Dockerfile.aws-cli

This image will be use as initContainer to copy the aws-cli to klusterlet-agent when initialized with awsirsa auth type.
This will allow us to keep registration-operator docker image clean.
Fixes # https://github.com/open-cluster-management-io/ocm/issues/514

:sparkles: Adding aws-cli to docker image

---

.github/workflows/post.yml
.github/workflows/releaseimage.yml
build/Dockerfile.aws-cli

Downloading proper awscli exe based on architecture
Fixes #https://github.com/open-cluster-management-io/ocm/issues/737

:bug: Fixing aws-cli image

---

pkg/registration/hub/manifests/rbac/managedcluster-clusterrolebinding.yaml
pkg/registration/hub/manifests/rbac/managedcluster-registration-rolebinding.yaml
pkg/registration/hub/manifests/rbac/managedcluster-work-rolebinding.yaml

Adding a second group, that will be used when the spoke starts registration with aws auth type. The aws solution uses [EKS access entries](https://docs.aws.amazon.com/eks/latest/userguide/creating-access-entries.html) and an access entry cannot contain a group name with "system:" prefix. More details can be found on [this](https://kubernetes.slack.com/archives/C01GE7YSUUF/p1733178937248749) slack thread.
> It can’t start with system:, eks:, aws:, amazon:, or iam:.
Fixes # https://github.com/open-cluster-management-io/ocm/issues/514

:sparkles: Adding second group for aws auth flow

---

solutions/argocd-agent/README.md

Fixes and clarifications to the Argo CD Agent integration solution: https://github.com/open-cluster-management-io/ocm/tree/main/solutions/argocd-agent

:book: Fixes and clarifications to the Argo CD Agent integration solution

---

solutions/joining-hub-and-spoke-with-aws-auth-manually/README.md
solutions/joining-hub-and-spoke-with-aws-auth-manually/templates/Template-Hub-Role-Permission-Policy.json
solutions/joining-hub-and-spoke-with-aws-auth-manually/templates/Template-Hub-Role-Trust-Policy.json
solutions/joining-hub-and-spoke-with-aws-auth-manually/templates/Template-Spoke-Role-Permission-Policy.json
solutions/joining-hub-and-spoke-with-aws-auth-manually/templates/Template-Spoke-Role-Trust-Policy.json
solutions/joining-hub-and-spoke-with-aws-auth-manually/templates/Template-hub-kubeconfig-secret.yaml

Adding manual steps to connect EKS clusters as Hub and spoke using OCM
Fixes #

:sparkles: Add manual steps to connect EKS clusters

---

test/e2e-test.mk

Fixes https://github.com/open-cluster-management-io/ocm/issues/755

🐛 Use e2e images instead of latest

---

go.mod
go.sum
manifests/cluster-manager/hub/0000_03_addon.open-cluster-management.io_addontemplates.crd.yaml
pkg/addon/templateagent/registration.go
pkg/addon/templateagent/registration_test.go
test/e2e/addonmanagement_test.go
test/e2e/manifests/addon/addon_template.yaml
test/e2e/manifests/addon/signca_secret_role.yaml
test/e2e/manifests/addon/signca_secret_rolebinding.yaml
vendor/modules.txt
vendor/open-cluster-management.io/api/addon/v1alpha1/0000_03_addon.open-cluster-management.io_addontemplates.crd.yaml
vendor/open-cluster-management.io/api/addon/v1alpha1/types_addontemplate.go
vendor/open-cluster-management.io/api/addon/v1alpha1/zz_generated.swagger_doc_generated.go

https://github.com/open-cluster-management-io/ocm/issues/688
Fixes #

✨ Allow Custom Signer signingCA to Specify Namespace in AddOnTemplate

---

pkg/registration/register/aws_irsa/aws_irsa.go
pkg/registration/register/aws_irsa/aws_irsa_test.go
pkg/registration/register/csr/csr.go
pkg/registration/register/interface.go
pkg/registration/register/secret_controller_test.go
pkg/registration/spoke/registration/creating_controller.go
pkg/registration/spoke/registration/creating_controller_test.go
pkg/registration/spoke/spokeagent.go
pkg/registration/spoke/spokeagent_test.go
test/integration/registration/clusterannotations_aws_test.go
test/integration/registration/spokecluster_aws_joining_test.go

Adding ManagedCluster annotations using a Decorator
Fixes #

:sparkles: Cluster decorator interface

---

go.mod
go.sum
pkg/registration/hub/importer/importer.go
pkg/registration/hub/importer/importer_test.go
pkg/registration/hub/importer/options/options.go
pkg/registration/hub/importer/providers/capi/provider.go
pkg/registration/hub/importer/providers/capi/provider_test.go
pkg/registration/hub/importer/providers/interface.go
pkg/registration/hub/importer/renderers.go
pkg/registration/hub/importer/renderers_test.go
pkg/registration/hub/manager.go
pkg/registration/hub/manager_test.go
test/integration/registration/integration_suite_test.go
test/integration/registration/managedcluster_importer_test.go
test/integration/testdeps/capi/cluster.x-k8s.io_clusters.yaml
vendor/modules.txt
vendor/open-cluster-management.io/api/feature/feature.go

✨ Add importer into registration

---

pkg/addon/templateagent/decorator.go
pkg/addon/templateagent/decorator_test.go
pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/template_agent_test.go
test/e2e/addonmanagement_test.go

This is a follow-up of PR https://github.com/open-cluster-management-io/ocm/pull/760, in this PR, it will handle the ca bundle for proxy config, a configmap containing the ca bundle will be created and mounted to the agent deployments/daemonsets. and the mounted ca bundle file path will be injected as the environment `CA_BUNDLE_FILE_PATH` to the deployments/daemonsets. Addon developers can use the environment to get the ca bundle data.
https://github.com/open-cluster-management-io/ocm/issues/761
Fixes #

✨ Add a configmap to handle the proxy ca bundle

---

pkg/registration/hub/lease/clocksynccontroller.go
pkg/registration/hub/lease/clocksynccontroller_test.go
pkg/registration/spoke/managedcluster/status_controller.go
test/integration/registration/managedcluster_lease_test.go

This patch aim to stop agents from updating managed cluster status when clock is already out of sync.
The issue occurs when the hub [sets the managed cluster status to unknown due to an outdated lease](https://github.com/stolostron/ocm/blob/16190e3a34d4b7dc6c1f2a039da0230b6aec850d/pkg/registration/hub/lease/controller.go#L148-L153), while the agent simultaneously [sets the managed cluster status to available because the API server is accessible](https://github.com/stolostron/ocm/blob/16190e3a34d4b7dc6c1f2a039da0230b6aec850d/pkg/registration/spoke/managedcluster/resource_reconcile.go#L52-L53). This conflict causes the managed cluster status to flap back and forth frequently, triggering numerous reconciliations and resulting in performance issues.

:bug: Agents stop update managedcluster status when clock is out of sync.

---

manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml

This is to ensure during upgrade scenario, the new operator can still start the old version of the agent.
Fixes #

🐛 Only enable auth driver when type is irsa

---

manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml
manifests/klusterlet/management/klusterlet-work-deployment.yaml
test/integration/util/aws.go

Add an initContainer to the Klusterlet deployment manifests and mount the awscli volume when using AWS IRSA-based authentication.
Update the test util function to check for both .aws and /awscli volume mounts.
Fixes # https://github.com/open-cluster-management-io/ocm/issues/514

✨ Mount the awscli volume when using AWS IRSA-based authentication.

---

pkg/work/spoke/apply/server_side_apply.go
pkg/work/spoke/apply/server_side_apply_test.go
test/e2e/work_workload_test.go

🐛 Ignore field should not be honored when creating the resource

---

pkg/work/spoke/controllers/manifestcontroller/manifestwork_controller.go
pkg/work/spoke/controllers/manifestcontroller/manifestwork_reconciler.go
pkg/work/spoke/spokeagent.go

🐛 fix work agent performance issue

---

pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/registration/register/aws_irsa/aws.go
pkg/registration/register/aws_irsa/aws_irsa.go
pkg/registration/register/aws_irsa/aws_irsa_test.go
pkg/registration/register/aws_irsa/aws_test.go
pkg/registration/register/aws_irsa/options.go
pkg/registration/spoke/spokeagent.go
test/integration/registration/spokecluster_aws_joining_test.go
test/integration/util/authentication.go

This PR has enhancement to complete the registration on spoke and save hub kubeconfig in a secret on spoke
Fixes https://github.com/open-cluster-management-io/ocm/issues/514

:sparkles: Completing aws registration on spoke

---

pkg/work/spoke/apply/server_side_apply.go
test/e2e/work_workload_test.go

🐛  Fix the issue that ownerref is not set with ignorefields

---

pkg/registration/OWNERS

Making guidewire members owner of aws registration
https://github.com/open-cluster-management-io/ocm/issues/514
Fixes #

:sparkles: Adding Guidewire team members to registration owners

---

pkg/operator/helpers/chart/config.go

the operator pod is pending because these fields are append to the deployment when nodeSelector is empty.
```
nodeSelector:
nodeSelectorTerms: ""
```
set nodeSelector to pointer, the fields will not be initialised if empty. 
Fixes #

:bug: set empty nodeselect to nil

---

solutions/joining-hub-and-spoke-with-aws-auth-manually/README.md

Removing manual step to generate the hub kube config secret
Fixes # [GWCP-65928](https://guidewirejira.atlassian.net/browse/GWCP-65928)

:sparkles: Removing manual step to generate the hub kube config secret

---

pkg/registration/hub/importer/importer.go
pkg/registration/hub/importer/providers/capi/provider.go
pkg/registration/hub/importer/providers/capi/provider_test.go
pkg/registration/hub/importer/renderers.go
test/integration/registration/managedcluster_importer_test.go

🌱  Check capi status if it is provisioned

---

pkg/registration/hub/importer/importer.go
pkg/registration/hub/importer/importer_test.go
pkg/registration/hub/importer/providers/capi/provider.go
pkg/registration/hub/importer/providers/capi/provider_test.go

requeue when the kubeconfig secret is not found. We cannot ensure that we always can get secret when capi cluster is in provisioned state.
Fixes #

 🌱 Requeue importer when secret is not found

---

pkg/cmd/spoke/operator.go
pkg/registration/hub/importer/renderers.go

when operator and agent run in the same namespace, they should use the different lease name.
Fixes #

🐛 Change the component name to klusterlet-agent

---

deploy/cluster-manager/chart/cluster-manager/templates/cluster_manager.yaml
deploy/cluster-manager/chart/cluster-manager/values.yaml

Changed cluster manager helm template to support setting the required registrationDrivers if present.
Ref: #514

:sparkles: ✨ feature feat: add registration drivers to cluster manager helm chart template.

---

deploy/klusterlet/chart/klusterlet/values.yaml
deploy/klusterlet/config/operator/operator.yaml
deploy/klusterlet/olm-catalog/latest/manifests/klusterlet.clusterserviceversion.yaml
pkg/operator/helpers/chart/render.go
pkg/registration/hub/importer/importer.go

:seedling: change replicas of klusterlet operator to 1

---

test/integration/operator/clustermanager_aws_test.go

:bug: fix integration test random failure

---

pkg/registration/hub/gc/controller.go
pkg/registration/hub/gc/controller_test.go
pkg/registration/hub/gc/gc_cluster_rbac.go
pkg/registration/hub/gc/gc_cluster_rbac_test.go
pkg/registration/hub/gc/gc_resources.go
pkg/registration/hub/gc/gc_resources_test.go
pkg/registration/hub/manager.go
test/integration/registration/managedcluster_deletion_test.go

the gc controller returned when cluster is empty, and the work rolebinding is left over.
this PR will handle the case that cluster is empty in gc controller.
Fixes #

:bug: fix gc controller not handle empty cluster

---

cmd/addon/main.go
cmd/placement/main.go
cmd/registration-operator/main.go
cmd/registration/main.go
cmd/work/main.go

This PR removes explicit calls to `rand.Seed(time.Now().UTC().UnixNano())` from multiple command entry points. As of Go 1.20, explicit seeding is unnecessary since the package is auto-initialized. This change removes the now-deprecated code and associated imports, cleaning up our codebase.
Go 1.20 no longer requires developers to manually seed the random number generator for typical operations. Removing these calls:
* Eliminates deprecation warnings.
* Simplifies the main functions.
* Reduces unnecessary code.
If deterministic random sequences are needed (for testing, for example), consider using rand.New(rand.NewSource(seed)) to initialize a local generator.

:seedling: Remove unnecessary random seed initialization.

---

pkg/work/spoke/apply/server_side_apply.go

there is a chance that owner ref apply is skipped when ignoreFields is set, which results in flaky e2e test.
Fixes #

🐛 Apply ownerref eventhough other field is ignored

---

solutions/argocd-agent/README.md

Doc fix to the argocd agent solution generate keys and cert file name typo.
The helm install command in the solution README for the argocd agent addon chart assumes the file name to be "tls" instead of "server". 
Fixes NA

:book: docs: fix the argocd agent solution generate keys and cert file name typo

---

solutions/deploy-argocd-apps/setup-ocm.sh

Argo CD push solution doc clusteradm init command should use the --wait param.
Fixes #

:book: docs: Argo CD push solution doc clusteradm init command should use the --wait param

---

.github/workflows/doc-only.yml

e2e hosted and singleton GitHub workflow should not be run on DOC-ONLY changes
Fixes NA

:seedling: chore: e2e hosted and singleton should not be run on DOC-ONLY changes

---

pkg/operator/helpers/chart/render.go
pkg/operator/helpers/chart/render_test.go
pkg/registration/hub/importer/importer.go
test/integration/registration/managedcluster_importer_test.go

Separate crd objects from others, so clusteradm can apply the crd objects first, after making sure the crd objects are created, then creates other resources.
https://github.com/open-cluster-management-io/clusteradm/issues/469#issuecomment-2712492158
Fixes #

🌱 Separate crd objects from others

---

pkg/registration/spoke/bootstrapkubeconfigs.go

Improve logging in selectBootstrapKubeConfigs function by replacing index with bootstrapKubeConfig in error and info messages for better clarity.

:seedling: Improve logging in selectBootstrapKubeConfigs function.

---

deploy/klusterlet/chart/klusterlet/templates/_helpers.tpl
deploy/klusterlet/chart/klusterlet/templates/agent-namespace.yaml
deploy/klusterlet/chart/klusterlet/templates/bootstrap_kubeconfig_secret.yaml
deploy/klusterlet/chart/klusterlet/templates/external_managedcluster-kubeconfig_secret.yaml
deploy/klusterlet/chart/klusterlet/templates/klusterlet.yaml
deploy/klusterlet/chart/klusterlet/values.yaml
pkg/operator/helpers/chart/config.go
pkg/operator/helpers/chart/render.go
pkg/operator/helpers/chart/render_test.go

1. support configure configure multiple hub kubeconfigs in klusterlet chart
2. fix the name of klusterlet agent namespace in different mode.
Fixes #

:seedling: support configure multiple hub kubeconfigs in klusterlet chart

---

solutions/kueue-admission-check/setup-env.sh

Installing Cluster Permissions in Kueue setup by Cluster- Permission helm chart and not directly with yaml files present in config/crds, config/rbac & config/deploy.
Fixes #903

:sparkles: replaced yaml files by helm chart

---

deploy/klusterlet/chart/klusterlet/templates/priority_class.yaml
pkg/operator/helpers/chart/render_test.go

when noOperator is true , that means the PriorityClass has been applied on the cluster, so there is no need to redeploy PriorityClass in this case.
Fixes #

:seedling: do not install PriorityClass if noOperator is true

---

SECURITY-INSIGHTS.yml

Fixes https://github.com/open-cluster-management-io/ocm/issues/863

📖 Add a security insights doc

---

pkg/operator/helpers/chart/config.go
pkg/operator/helpers/chart/render_test.go
pkg/registration/hub/importer/importer.go

The type of ResourceRequirement in klusterlet spec is Enum=Default;BestEffort;ResourceRequirement, will be empty if not set in KlusterletChartConfig to render helm chart, and will be failed to apply the klusterlet with empty type.
Fixes #

:bug: fix empty type of ResourceRequirement if ResourceRequirement is empty

---

deploy/klusterlet/chart/klusterlet/README.md
deploy/klusterlet/chart/klusterlet/templates/_helpers.tpl
deploy/klusterlet/chart/klusterlet/templates/cluster_role.yaml
deploy/klusterlet/chart/klusterlet/templates/cluster_role_binding.yaml
deploy/klusterlet/chart/klusterlet/templates/klusterlet.yaml
deploy/klusterlet/chart/klusterlet/templates/operator.yaml
deploy/klusterlet/chart/klusterlet/templates/priority_class.yaml
deploy/klusterlet/chart/klusterlet/templates/service_account.yaml
pkg/operator/helpers/chart/render_test.go

1. correct the definition of  agentNamespace and differentiate between agentNamespace and klusterletNamespace:
agentNamespace is the klusterlet name in hosted mode.
agentNamespace is the klusterlet.namespace in default mode.
agentNamespace is open-cluster-management-agent if klusterlet.namespace is empty in default mode.
2. separate hosted mode from `noOperator = true` because noOperator = true is a special case,  could be hosted mode or default mode.
Fixes #

:bug: fix incorrect agent namespace in klusterlet helm chart

---

go.mod
go.sum
pkg/placement/controllers/metrics/metrics.go
pkg/placement/controllers/scheduling/scheduling_controller.go
pkg/placement/helpers/cel.go
pkg/placement/helpers/cel_test.go
pkg/placement/helpers/clusters.go
pkg/placement/helpers/clusters_test.go
pkg/placement/plugins/predicate/predicate.go
vendor/modules.txt
vendor/open-cluster-management.io/sdk-go/pkg/cel/common/values.go
vendor/open-cluster-management.io/sdk-go/pkg/cel/library/cost.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/clients/utils/utils.go

https://github.com/open-cluster-management-io/ocm/issues/843
https://github.com/open-cluster-management-io/ocm/issues/955
Per expression cost limit exceeded
```
I0424 09:55:58.810235       1 cel.go:175] "Expression evaluation failed" rule="managedCluster.metadata.labels[\"test\"] == \"true\"" cluster="cluster1" err="operation cancelled: actual cost limit exceeded"
```
Total expression cost budget exceeded
```
I0424 09:21:39.903577       1 cel.go:206] "Cost budget exceeded" rule="managedCluster.metadata.labels[\"test\"] == \"true\"" cost=5 budget=0
```
Metrics
```
scheduling_cel_runtime_duration_seconds_bucket{name="placement_scheduling",le="1e-06"} 0
scheduling_cel_runtime_duration_seconds_bucket{name="placement_scheduling",le="9.999999999999999e-06"} 0 …
```

:sparkles: add cost budget, runtime cost estimator and metrics

---

solutions/joining-hub-and-spoke-with-aws-auth/README.md

We want to update our example docs for joining hub and spoke through AWSIRSA to not pass --bundle-version latest and instead just use default (pass nothing)
Fixes #

:book: Update docs for joining hubspoke awsirsa to not use bundle version latest but default

---

pkg/common/helpers/cel.go
pkg/placement/helpers/cel.go

Extracting CEL evaluation/budgeting functions from the placement CELSelector into the common package so that they can be used for CEL eval across OCM. Need pretty much the same thing for #910, so may as well have generic functions that can be used anywhere.
Could also pull these out into the sdk-go cel package if preferred. Thought I'd start with this and see what others think.
https://github.com/open-cluster-management-io/ocm/pull/964
https://github.com/open-cluster-management-io/ocm/pull/910

🌱 Common CEL evaluation functions

---

pkg/registration/register/aws_irsa/hub_driver.go

Delete the access entry first and then delete the IAM role created by registration controller since deleting the IAM role first also seems to remove the access entry and the access entry deletion fails. Also add a check after deletion of access entry and ignore the error if it returns "resourceNotFound".
Fixes #1010

🐛 Switch the order of deletion of access entry and iamrole when managedcluster gets deleted.

---

pkg/registration/register/common.go

the ut can pass when run locally, but fail when run in pod.
because if HubKubeconfigFile is empty clientcmd.BuildConfigFromFlags will use the restclient.InClusterConfig() to get kubeConfig in pod. 
The failed ut 
https://github.com/open-cluster-management-io/ocm/blob/215cfed77e52b13e1b409d6d03866669ef77bc57/pkg/registration/register/common_test.go#L315-L321
Fixes #

:bug: fix the ut failure in pod
