open-cluster-management-io/ocm

SECURITY.md

Update security md to refer to the common OCM community security md file

---

README.md

Add OCM CII best pratice badge

---

README.md

Signed-off-by: yue9944882 <291271447@qq.com>

Chore: Apache license badge

---

README.md

> Signed-off-by: yue9944882 <291271447@qq.com>
/cc @qiujian16 @luckyfengyong

Doc: Citing kubevela integration

---

solutions/deploy-a-helm-chart/README.md
solutions/deploy-a-helm-chart/manifests/clusterset.yaml
solutions/deploy-a-helm-chart/manifests/clustersetbinding.yaml
solutions/deploy-a-helm-chart/manifests/placement.yaml
solutions/deploy-a-helm-chart/manifests/subscription.yaml
solutions/setup-dev-environment/local-up.sh

Hello
I've been going through the development environment and deploy helm chart instructions,
I bumped into a couple of small modifications required to make this work.

Small fixes to current documentation and manifests

---

solutions/deploy-a-helm-chart/deploy.sh
solutions/deploy-a-helm-chart/manifests/clusterset.yaml
solutions/deploy-a-helm-chart/manifests/clustersetbinding.yaml
solutions/deploy-a-helm-chart/manifests/placement.yaml
solutions/deploy-manifests/README.md
solutions/deploy-manifests/manifests/nginx.yaml

Add deploy manifests

---

solutions/access-remote-api/README.md
solutions/access-remote-api/manifests/clusterrolebinding.yaml
solutions/access-remote-api/manifests/managed-sa.yaml

Access spoke api using cluster-proxy

---

README.md

Signed-off-by: maoyangLiu <liumaoyang@inspur.com>
The old link has expired, I think the link I submitted is the correct one

fix 404 url

---

troubleshooting/setup-ocm.md

for https://github.com/open-cluster-management-io/OCM/issues/50

Add a common OCM setup troubleshooting guide

---

solutions/run-multicluster-servicemesh/README.md
solutions/run-multicluster-servicemesh/manifests/destinationrule-cluster2.yaml
solutions/run-multicluster-servicemesh/manifests/meshdeployment.yaml
solutions/run-multicluster-servicemesh/manifests/meshfederation.yaml
solutions/run-multicluster-servicemesh/manifests/serviceentry-export-cluster2.yaml
solutions/run-multicluster-servicemesh/manifests/serviceentry-import-cluster1.yaml
solutions/run-multicluster-servicemesh/manifests/virtualservice-cluster1.yaml

ref: https://github.com/open-cluster-management-io/OCM/issues/34
Signed-off-by: morvencao <lcao@redhat.com>

add multicluster service mesh solution.

---

README.md

Update youtube URL

---

solutions/deploy-argocd-apps/README.md
solutions/deploy-argocd-apps/cluster1-config.yaml
solutions/deploy-argocd-apps/cluster2-config.yaml
solutions/deploy-argocd-apps/manifests/guestbook-app-placement.yaml
solutions/deploy-argocd-apps/manifests/guestbook-app.yaml
solutions/deploy-argocd-apps/manifests/ocm-placement-consumer-role.yaml
solutions/deploy-argocd-apps/manifests/ocm-placement-consumer-rolebinding.yaml
solutions/deploy-argocd-apps/manifests/ocm-placement-generator-cm.yaml
solutions/deploy-argocd-apps/setup-argocd.sh
solutions/deploy-argocd-apps/setup-ocm.sh

Signed-off-by: Yang Le <yangle@redhat.com>

add a solution to deploy argocd apps

---

solutions/migrate-kubefed/README.md

Add Kubefed to Open Cluster Management migration guide

---

solutions/deploy-argocd-apps/README.md

Signed-off-by: Maggie Chen <magchen@redhat.com>

Add more doc for finding the ip address

---

controlplane/hack/deploy-ocm-controlplane.sh
controlplane/hack/deploy/deployment.yaml
controlplane/hack/deploy/kustomization.yaml
controlplane/hack/deploy/route.yaml
controlplane/hack/deploy/service.yaml

Add deploy scripts

---

controlplane/.gitignore
controlplane/Dockerfile
controlplane/README.md
controlplane/cmd/server/start.go
controlplane/config/hub/bootstrap.go
controlplane/hack/deploy-ocm-controlplane.sh
controlplane/hack/deploy/deployment.yaml
controlplane/hack/deploy/kustomization.yaml
controlplane/hack/deploy/service.yaml
controlplane/hack/start-ocm-controlplane.sh
controlplane/pkg/apiserver/controlplane.go
controlplane/pkg/controllers/kubecontroller/options/options.go

also modified the local start controlplane script

add deploy-ocm-controlplane script

---

controlplane/README.md

Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>

update readme: warning clusteradm version

---

controlplane/hack/lib/util.sh
controlplane/plugin/admission/managedclustermutating/admission.go
controlplane/plugin/admission/managedclustersetbindingvalidating/admission.go
controlplane/plugin/admission/managedclustervalidating/admission.go

Fix wrong type error in admission

---

controlplane/Makefile
controlplane/hack/deploy/addon/policy/hub/crds/apps.open-cluster-management.io_placementrules_crd.yaml
controlplane/hack/deploy/addon/policy/hub/crds/kustomization.yaml
controlplane/hack/deploy/addon/policy/hub/crds/policy.open-cluster-management.io_placementbindings.yaml
controlplane/hack/deploy/addon/policy/hub/crds/policy.open-cluster-management.io_policies.yaml
controlplane/hack/deploy/addon/policy/hub/crds/policy.open-cluster-management.io_policyautomations.yaml
controlplane/hack/deploy/addon/policy/hub/crds/policy.open-cluster-management.io_policysets.yaml
controlplane/hack/deploy/addon/policy/hub/kustomization.yaml
controlplane/hack/deploy/addon/policy/propagator/grc-policy-propagator-deployment.yaml
controlplane/hack/deploy/addon/policy/propagator/grc-policy-propagator-metrics-service.yaml
controlplane/hack/deploy/addon/policy/propagator/grc-policy-propagator-role.yaml
controlplane/hack/deploy/addon/policy/propagator/grc-policy-propagator-rolebinding.yaml
controlplane/hack/deploy/addon/policy/propagator/grc-policy-propagator-serviceaccount.yaml
controlplane/hack/deploy/addon/policy/propagator/kustomization.yaml

Signed-off-by: morvencao <lcao@redhat.com>

deploy policy propagator to standalone controlplane.

---

controlplane/README.md
controlplane/hack/demo/README.md
controlplane/hack/demo/next-generation.sh
controlplane/hack/deploy-ocm-controlplane.sh

Signed-off-by: morvencao <lcao@redhat.com>

make host_postfix optional when setting up ocm control plane

---

.github/workflows/e2e-placement.yml
.github/workflows/e2e-registration-operator.yml
.github/workflows/e2e-registration.yml
.github/workflows/e2e-work.yml
.github/workflows/post.yml
.github/workflows/pre.yml

The github action doc: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore

Update: ignore changes on docs/solutions in github actions.

---

pkg/operator/OWNERS
pkg/placement/OWNERS
pkg/registration/OWNERS
pkg/work/OWNERS
test/OWNERS

🌱 Add owner file for sub project

---

manifests/cluster-manager/hub/cluster-manager-manifestworkreplicaset-clusterrole.yaml
pkg/registration/hub/clusterrole/manifests/managedcluster-work-clusterrole.yaml
pkg/work/helper/helper_test.go
pkg/work/helper/helpers.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_add_finalizer_reconcile.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_add_finalizer_test.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_controller.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_controllers_test.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_deploy_reconcile.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_deploy_test.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_finalize_reconcile.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_finalizer_test.go
pkg/work/hub/test/helper.go
pkg/work/spoke/controllers/appliedmanifestcontroller/appliedmanifestwork_controller.go
pkg/work/spoke/controllers/appliedmanifestcontroller/appliedmanifestwork_controller_test.go
pkg/work/spoke/controllers/finalizercontroller/add_finalizer_controller.go
pkg/work/spoke/controllers/finalizercontroller/add_finalizer_controller_test.go
pkg/work/spoke/controllers/finalizercontroller/appliedmanifestwork_finalize_controller.go
pkg/work/spoke/controllers/finalizercontroller/appliedmanifestwork_finalize_controller_test.go
pkg/work/spoke/controllers/finalizercontroller/manifestwork_finalize_controller.go
pkg/work/spoke/controllers/finalizercontroller/manifestwork_finalize_controller_test.go
pkg/work/spoke/controllers/finalizercontroller/unmanaged_appliedmanifestwork_controller.go
pkg/work/spoke/controllers/finalizercontroller/unmanaged_appliedmanifestwork_controller_test.go
pkg/work/spoke/controllers/manifestcontroller/manifestwork_controller.go
pkg/work/spoke/controllers/manifestcontroller/manifestwork_controller_test.go
pkg/work/spoke/controllers/statuscontroller/availablestatus_controller.go
pkg/work/spoke/controllers/statuscontroller/availablestatus_controller_test.go
pkg/work/spoke/spokeagent.go

🌱 Use patcher in work

---

pkg/addon/controllers/addonconfiguration/addon_configuration_reconciler.go
pkg/addon/controllers/addonconfiguration/controller.go
pkg/addon/controllers/addonconfiguration/mgmt_addon_progressing_reconciler.go
pkg/addon/controllers/addonconfiguration/mgmt_addon_progressing_reconciler_test.go
pkg/addon/controllers/addonprogressing/controller.go
pkg/addon/controllers/managementaddoninstallprogression/controller.go

So we remove the redundant patch code
Fixes #

 🌱  Use patcher in addon manager code

---

.github/workflows/e2e.yml
manifests/cluster-manager/hub/cluster-manager-addon-manager-clusterrole.yaml
manifests/cluster-manager/hub/cluster-manager-addon-manager-work-executor-admin-clusterrolebinding.yaml
manifests/cluster-manager/hub/cluster-manager-work-executor-admin-clusterrole.yaml
pkg/addon/controllers/addontemplate/controller.go
pkg/addon/templateagent/template_agent_test.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller_test.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_hub_reconcile.go
test/e2e/addon_lease_test.go
test/e2e/addon_test.go
test/e2e/addonmanagement_test.go
test/e2e/common.go
test/e2e/manifests/addon/addon_deployment_config.yaml
test/e2e/manifests/addon/addon_template.yaml
test/e2e/manifests/addon/cluster_management_addon.yaml
test/e2e/manifests/addon/cluster_role.yaml
test/e2e/manifests/testfs.go
test/integration/operator/clustermanager_hosted_test.go
test/integration/operator/clustermanager_test.go

Add e2e test for addon manager
This is a follow-up for https://github.com/open-cluster-management-io/ocm/pull/196
https://github.com/open-cluster-management-io/ocm/issues/128

🌱 add e2e tests for addon manager

---

manifests/cluster-manager/hub/cluster-manager-placement-clusterrole.yaml

Add  subjectaccessreviews permission for placement in order to access debug path.
Fixes #

🐛 add subjectaccessreviews permission for placement

---

solutions/OWNERS

Update OWNERS file to better reflect the approvers for post OCM foundation code consolidation.
NA
Fixes #
NA

:book: Update OWNERS file post code consolidation

---

test/integration/placement/assertion_test.go
test/integration/placement/placement_test.go
test/integration/placement/prioritizer_test.go
test/integration/placement/toleration_test.go

Replace placement integration testing code Update(), UpdateStatus() with PatchSpec and PatchStatus().
Fixes #

:seedling: update placement integration testing code with patcher 

---

pkg/cmd/hub/addon.go
pkg/cmd/hub/operator.go
pkg/cmd/hub/placement.go
pkg/cmd/hub/registration.go
pkg/cmd/hub/work.go
pkg/cmd/spoke/operator.go
pkg/cmd/spoke/registration.go
pkg/cmd/spoke/work.go
pkg/common/options/agent.go
pkg/common/options/options.go
pkg/common/options/options_test.go

so we can set leader and qps related setting for all controllers
Fixes #

🌱 Build a commonoption for all managers

---

Makefile
deploy/cluster-manager/PROJECT
deploy/cluster-manager/olm-catalog/cluster-manager/manifests/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/manifests/operator.open-cluster-management.io_clustermanagers.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/metadata/annotations.yaml
deploy/klusterlet/PROJECT
deploy/klusterlet/config/operator/operator.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/operator.open-cluster-management.io_klusterlets.yaml
deploy/klusterlet/olm-catalog/klusterlet/metadata/annotations.yaml

:seedling:  update pod securitycontext and upgrade operator sdk version

---

deploy/klusterlet/config/samples/operator_open-cluster-management_klusterlets.cr.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/klusterlet.clusterserviceversion.yaml
pkg/operator/helpers/helpers.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_runtime_reconcile.go
pkg/operator/operators/klusterlet/controllers/statuscontroller/klusterlet_status_controller.go
pkg/work/helper/helpers.go
test/integration/work/manifestworkreplicaset_test.go

🐛 Remove old agent when upgrade to singleton

---

pkg/operator/operators/klusterlet/controllers/bootstrapcontroller/bootstrapcontroller.go
pkg/operator/operators/klusterlet/controllers/bootstrapcontroller/bootstrapcontroller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_runtime_reconcile.go

🐛 correct the agent deployment name in different install mode

---

solutions/run-multicluster-servicemesh/README.md
solutions/run-multicluster-servicemesh/manifests/meshdeployment.yaml

This PR tries to upgrade Istio version from 1.13.2 to 1.16.7 for the server mesh addon on OCM.
Fixes # https://github.com/open-cluster-management-io/ocm/issues/271

🐛 update istio version.

---

pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller_test.go

:bug: delete klusterlet if the managed cluster refused the connection

---

manifests/klusterletkube111/klusterlet-work-clusterrolebinding.yaml

:bug: fix work sa name in old kube cluster

---

manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-work-deployment.yaml
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
test/integration/operator/klusterlet_test.go

:seedling: set work agent status-sync-interval when the replica is 1

---

.github/workflows/release.yml
go.mod
go.sum
vendor/modules.txt

🌱 Upgrade addon-framework library to 0.8.0

---

.github/workflows/releaseimage.yml

🐛 Fix release image manifest error

---

go.mod
go.sum
pkg/addon/controllers/addonconfiguration/graph.go
pkg/addon/controllers/addonconfiguration/graph_test.go
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/manager/controllers/addonconfiguration/graph.go
vendor/open-cluster-management.io/api/cluster/v1alpha1/helpers.go
vendor/open-cluster-management.io/api/cluster/v1alpha1/zz_generated.deepcopy.go

:seedling: upgrade addon rollout library 

---

.github/workflows/ossf-scorecard.yml

https://github.com/open-cluster-management-io/ocm/issues/296
Fixes #

:seedling: Use ossf score card

---

README.md

https://github.com/open-cluster-management-io/ocm/issues/296
Fixes #

:seedling: Add open ssf scorecard badge

---

solutions/multiple-hubs-hosted/README.md
solutions/multiple-hubs-hosted/setup-hub1.sh
solutions/multiple-hubs-hosted/setup-hub2.sh
solutions/multiple-hubs/README.md
solutions/multiple-hubs/setup-hub1.sh
solutions/multiple-hubs/setup-hub2.sh

📖 add solutions of multiple hubs

---

README.md

Add fossa license scanning badge
https://github.com/open-cluster-management-io/ocm/issues/296
Fixes #

:seedling: Add fossa license scanning badge

---

solutions/multiple-hubs-hosted/README.md
solutions/multiple-hubs-hosted/setup-hub2.sh

🐛 fix the wrong endpoint issue of the multiple hubs hosted solution

---

.github/workflows/release.yml

🐛 Reduce permision for release gha

---

go.mod
go.sum
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/default_sync.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/healthcheck_sync.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/hosted_sync.go

:seedling: Bump addon framework to the latest version

---

.github/workflows/cloudevents-integration.yml
go.mod
go.sum
test/integration/cloudevents/source/source.go
vendor/modules.txt
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/agentclient.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/interface.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/mqtt/agentoptions.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/mqtt/options.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/mqtt/sourceoptions.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/sourceclient.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/types/types.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/agent/client/manifestwork.go

:seedling: update sdk-go to update work clients mqtt topics

---

go.mod
go.sum
vendor/modules.txt
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/mqtt/options.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/types/types.go

:seedling: update sdk-go lib

---

go.mod
go.sum
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/addonfactory.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/healthcheck_sync.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/managementaddon/controller.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/manager.go
vendor/open-cluster-management.io/addon-framework/pkg/agent/inteface.go

🌱 Upgrade addon framework

---

Makefile
deploy/cluster-manager/config/manifests/bases/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/0.13.0/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/0.13.0/operator.open-cluster-management.io_clustermanagers.yaml
deploy/cluster-manager/olm-catalog/cluster-manager/cluster-manager.package.yaml
deploy/klusterlet/config/samples/operator_open-cluster-management_klusterlets.cr.yaml
deploy/klusterlet/olm-catalog/klusterlet/0.13.0/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/klusterlet/0.13.0/operator.open-cluster-management.io_klusterlets.yaml
deploy/klusterlet/olm-catalog/klusterlet/klusterlet.package.yaml
deploy/klusterlet/olm-catalog/klusterlet/manifests/klusterlet.clusterserviceversion.yaml

:seedling: bump csv to 0.14

---

go.mod
go.sum
vendor/modules.txt
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/mqtt/agentoptions.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/mqtt/options.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/mqtt/sourceoptions.go

:seedling: update sdk-go deps

---

.github/workflows/pre.yml
pkg/registration/hub/csr/controller_test.go
pkg/registration/hub/csr/reconciler.go
pkg/registration/hub/managedcluster/controller.go
pkg/registration/hub/managedcluster/controller_test.go
pkg/registration/hub/manager.go
test/integration/registration/clusterannotations_test.go
test/integration/registration/spokecluster_autoapproval_test.go

🐛 avoid cluster auto approve failed occasionally

---

.github/dependabot.yml

🌱 Add dependabot to auto update dependencies

---

.github/workflows/ossf-scorecard.yml

Fixes #https://github.com/open-cluster-management-io/ocm/actions/runs/8585964547/job/23527922367

:seedling: Bump ossf/scorecard-action to 2.3.1

---

pkg/addon/controllers/addontemplate/controller.go
pkg/addon/templateagent/registration_test.go
pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/template_agent_test.go

Fixes #https://github.com/open-cluster-management-io/ocm/issues/387

🐛 Set a fixed agent name for the template type addon

---

go.mod
go.sum
vendor/modules.txt
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/agentclient.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/baseclient.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/grpc/agentoptions.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/grpc/options.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/grpc/sourceoptions.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/mqtt/agentoptions.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/mqtt/options.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/mqtt/sourceoptions.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/options/options.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/agent/handler/resourcehandler.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/source/client/manifestwork.go

Followup PR for https://github.com/open-cluster-management-io/sdk-go/pull/28
update sdk-go dependency to make sure work agent apply manifestwork correctly, to build work docker image that can be used in addon-framework e2e testing.
Fixes #

🌱 update sdk-go dependency.

---

build/Dockerfile.addon
build/Dockerfile.placement
build/Dockerfile.registration
build/Dockerfile.registration-operator
build/Dockerfile.work

:seedling:  upgrade base image from ubi8 to ubi9

---

pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/values.go
pkg/addon/templateagent/values_test.go

Fixes #https://github.com/open-cluster-management-io/ocm/pull/417#discussion_r1574335522

🌱 Refactor template addon get values func

---

.github/workflows/post.yml
.github/workflows/pre.yml

codecov-action doesn't support tokenless upload since v4: https://github.com/codecov/codecov-action/issues/1292

:bug: Add codecov token back.

---

Makefile
deploy/cluster-manager/config/manifests/bases/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/0.13.2/manifests/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/0.13.2/manifests/operator.open-cluster-management.io_clustermanagers.yaml
deploy/cluster-manager/olm-catalog/0.13.2/metadata/annotations.yaml
deploy/klusterlet/config/manifests/bases/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/0.13.2/manifests/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/0.13.2/manifests/operator.open-cluster-management.io_klusterlets.yaml
deploy/klusterlet/olm-catalog/0.13.2/metadata/annotations.yaml
deploy/klusterlet/olm-catalog/latest/manifests/klusterlet.clusterserviceversion.yaml

:seedling: bump csv to 0.13.2

---

deploy/cluster-manager/config/manifests/bases/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/0.13.0/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/0.13.1/manifests/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/0.13.2/manifests/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/latest/manifests/cluster-manager.clusterserviceversion.yaml
deploy/klusterlet/config/manifests/bases/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/0.13.0/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/0.13.1/manifests/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/0.13.2/manifests/klusterlet.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/latest/manifests/klusterlet.clusterserviceversion.yaml
pkg/features/feature.go

:seedling: update provider name

---

ADOPTERS.md

Add an adopters file for the existing adopters that correspond with the website https://open-cluster-management.io/
Fixes #

:book: docs: add adopters file for existing ocm adopters

---

ADOPTERS.md

🌱 Add appscode to ADOPTERS list

---

pkg/placement/controllers/scheduling/scheduling_controller.go
pkg/placement/controllers/scheduling/scheduling_controller_test.go
pkg/placement/helpers/testing/builders.go
test/integration/placement/placement_test.go

Fixes #https://github.com/open-cluster-management-io/ocm/issues/472

🐛 Exclude terminating clusters from Placementdecision

---

ADOPTERS.md

Add RamenDR to ADDOPTERS list.

:seedling: Add RamenDR project to ADOPTERS

---

pkg/work/webhook/start.go

🐛 Fix "log.SetLogger(...) was never called" in wrok-webhook

---

solutions/deploy-a-helm-chart/README.md

🐛 Fix addon enable command

---

pkg/registration/hub/lease/controller.go
pkg/registration/spoke/managedcluster/status_controller.go

🌱 Refine the cluster available event messages

---

pkg/registration/clientcert/certificate.go
pkg/registration/hub/csr/reconciler.go
pkg/registration/hub/manager.go

using managed cluster instead of spoke in log message
Fixes #393

:bug:  using managed cluster instead of spoke in log msg

---

pkg/cmd/spoke/operator.go
pkg/cmd/spoke/registration.go
pkg/cmd/spoke/work.go
pkg/common/options/agent.go

🌱 Fix typo: Rename 'CommoOpts' to 'CommonOpts'

---

go.mod
go.sum
test/integration/cloudevents/source/handler.go
test/integration/cloudevents/source/manifestwork.go
test/integration/cloudevents/source/source.go
test/integration/cloudevents/source/watcher.go
vendor/modules.txt
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/agent/client/manifestwork.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/agent/lister/lister.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/clientbuilder.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/internal/clientset.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/source/client/manifestwork.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/source/lister/lister.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/store/base.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/store/informer.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/store/interface.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/store/local.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/utils/utils.go

:seedling: upgrade sdk-go

---

manifests/klusterlet/managed/klusterlet-registration-clusterrole-addon-management.yaml
manifests/klusterlet/managed/klusterlet-registration-clusterrole.yaml
manifests/klusterlet/managed/klusterlet-registration-clusterrolebinding-addon-management.yaml
manifests/klusterlet/managed/klusterlet-registration-clusterrolebinding.yaml
manifests/klusterlet/managed/klusterlet-registration-serviceaccount.yaml
manifests/klusterlet/managed/klusterlet-work-clusterrole-execution.yaml
manifests/klusterlet/managed/klusterlet-work-clusterrole.yaml
manifests/klusterlet/managed/klusterlet-work-clusterrolebinding-aggregate.yaml
manifests/klusterlet/managed/klusterlet-work-clusterrolebinding-execution-admin.yaml
manifests/klusterlet/managed/klusterlet-work-clusterrolebinding-execution.yaml
manifests/klusterlet/managed/klusterlet-work-clusterrolebinding.yaml
manifests/klusterlet/managed/klusterlet-work-serviceaccount.yaml
manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-clusterrole-addon-management.yaml
manifests/klusterlet/management/klusterlet-registration-clusterrolebinding-addon-management.yaml
manifests/klusterlet/management/klusterlet-registration-deployment.yaml
manifests/klusterlet/management/klusterlet-registration-role.yaml
manifests/klusterlet/management/klusterlet-registration-rolebinding-extension-apiserver.yaml
manifests/klusterlet/management/klusterlet-registration-rolebinding.yaml
manifests/klusterlet/management/klusterlet-registration-serviceaccount.yaml
manifests/klusterlet/management/klusterlet-role-extension-apiserver.yaml
manifests/klusterlet/management/klusterlet-work-deployment.yaml
manifests/klusterlet/management/klusterlet-work-role.yaml
manifests/klusterlet/management/klusterlet-work-rolebinding-extension-apiserver.yaml
manifests/klusterlet/management/klusterlet-work-rolebinding.yaml
manifests/klusterlet/management/klusterlet-work-serviceaccount.yaml
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
test/integration/operator/klusterlet_test.go

https://github.com/open-cluster-management-io/ocm/issues/530
Fixes #

:bug: fix the label cannot be number

---

cmd/placement/main.go

:seedling: enable log flags for placement

---

pkg/registration/clientcert/cert_controller.go
pkg/registration/clientcert/controller_test.go
pkg/registration/spoke/addon/registration_controller.go
pkg/registration/spoke/spokeagent.go
test/integration/registration/spokeagent_rebootstrap_test.go

🌱 make additional secret data always sensitive

---

go.mod
go.sum
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/healthcheck_sync.go
vendor/open-cluster-management.io/addon-framework/pkg/utils/probe_helper.go

🌱 Bump addon framework to the latest version

---

go.mod
go.sum
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/healthcheck_sync.go
vendor/open-cluster-management.io/addon-framework/pkg/utils/probe_helper.go

🌱 [release-0.14] Bump addon framework to the latest version

---

test/e2e/klusterlet_hosted_test.go

Change the timeout usage to default usage.

:seedling: Using default timeout in hosted cases.

---

pkg/registration/OWNERS

Add xuezhaojun in registration OWNERS file to approve/review the changes relate to "MultipleHubs"

:seedling: Add xuezhaojun in registration owners.

---

pkg/work/spoke/options.go
pkg/work/spoke/spokeagent.go
pkg/work/spoke/spokeagent_test.go
test/integration/work/work_test.go

Fixes https://github.com/open-cluster-management-io/ocm/issues/586

🐛 Set default user-agent for work to work-agent

---

CONTRIBUTING.md

📖 Update contributing guide

---

deploy/cluster-manager/chart/cluster-manager/templates/bootstrap_cluster_role.yaml
deploy/cluster-manager/chart/cluster-manager/templates/bootstrap_sa.yaml
deploy/cluster-manager/chart/cluster-manager/templates/bootstrap_sa_cluster_role_binding.yaml
deploy/cluster-manager/chart/cluster-manager/templates/cluster_manager.yaml
deploy/cluster-manager/chart/cluster-manager/values.yaml
deploy/cluster-manager/chart/config.go
pkg/operator/helpers/chart/render.go
pkg/operator/helpers/chart/render_test.go

:bug: fix issues in operator helm chart

---

deploy/cluster-manager/chart/cluster-manager/templates/_helpers.tpl
deploy/cluster-manager/chart/cluster-manager/templates/bootstrap_token_secret.yaml
deploy/cluster-manager/chart/cluster-manager/templates/cluster_manager.yaml
deploy/cluster-manager/chart/cluster-manager/values.yaml
pkg/operator/helpers/chart/render_test.go

:bug:  fix token-secret format

---

.github/workflows/chart-upload.yml
.github/workflows/release.yml
.github/workflows/releaseimage.yml

🌱 Add chart action into release

---

pkg/registration/hub/manifests/rbac/managedcluster-clusterrole.yaml
pkg/registration/hub/manifests/rbac/managedcluster-clusterrolebinding.yaml
pkg/registration/hub/manifests/rbac/managedcluster-registration-rolebinding.yaml
pkg/registration/hub/manifests/rbac/managedcluster-work-rolebinding.yaml

If the cluster name is digital, the label value which is the cluster name should be a string.
Fixes #

:bug:fix the cluster name is digital

---

.github/workflows/chart-upload.yml
.github/workflows/release.yml
.github/workflows/releaseimage.yml

🐛 Fix typo of trimmed release version

---

.github/workflows/chart-upload.yml
.github/workflows/release.yml
pkg/addon/templateagent/testmanifests/addontemplate.yaml
pkg/addon/templateagent/testmanifests/addontemplate_daemonset.yaml
pkg/addon/templateagent/testmanifests/addontemplate_deployment.yaml
test/integration/addon/testmanifests/addontemplate.yaml

🐛 Add trimmed release version to env

---

.github/workflows/release.yml

🐛 Fix wrong helm chart location

---

.github/workflows/release.yml

🐛 Fix helm chart version

---

test/integration/addon/addon_manager_template_test.go

Fixes #https://github.com/open-cluster-management-io/ocm/issues/651

:bug: generate mca before testing rollout

---

pkg/registration/helpers/testing/testinghelpers.go
pkg/registration/hub/lease/controller.go
pkg/registration/hub/lease/controller_test.go
pkg/registration/hub/managedcluster/controller_test.go

🐛 handle the unknown status of the previously accepted cluster

---

.github/workflows/release.yml

Fixes #https://github.com/open-cluster-management-io/ocm/issues/662

🐛 Use release version for appVersion rather than trimmed version

---

pkg/registration/hub/managedcluster/controller.go

🐛 Return false when accept return error

---

pkg/work/webhook/start.go
pkg/work/webhook/v1alpha1/manifestworkreplicaset_validating.go
pkg/work/webhook/v1alpha1/manifestworkreplicaset_validating_test.go

✨ Register ManifestWorkReplicaSet webhook when feature is enabled

---

pkg/registration/spoke/bootstrapkubeconfigs.go
pkg/registration/spoke/spokeagent.go
pkg/registration/spoke/spokeagent_test.go

🐛 Use context cancel func to trigger reselect

---

test/integration/registration/managedcluster_deletion_test.go

This pull request updates the test cases in `managedcluster_deletion_test.go` to check for errors directly instead of returning boolean values. This change enhances the clarity of error reporting when test cases fail, allowing for more informative messages regarding the specific issues encountered.
* Modified gomega.Eventually assertions to return error instead of bool.
* Updated error handling to provide detailed messages when conditions are not met, improving the debugging experience

:seedling: Check `error` instead of `bool` to see error msg when case fails.

---

pkg/registration/helpers/testing/testinghelpers.go
pkg/registration/register/aws_irsa/aws_irsa_test.go
pkg/registration/register/common.go
pkg/registration/register/common_test.go
pkg/registration/register/csr/csr_test.go
pkg/registration/spoke/health_checker_test.go
pkg/registration/spoke/registration/secret_controller_test.go

🌱 support CA file in the bootstrap hub kubeconfig

---

go.mod
go.sum
pkg/work/hub/manager.go
pkg/work/spoke/spokeagent.go
vendor/modules.txt
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/agentclient.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/baseclient.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/metrics_collector.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/generic/sourceclient.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/agent/client/manifestwork.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/source/client/manifestwork.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/work/store/informer.go

refer to https://github.com/open-cluster-management-io/sdk-go/pull/88

🐛 update sdk-go to fix unstable test 

---

pkg/addon/controllers/addonconfiguration/addon_configuration_reconciler_test.go
pkg/addon/controllers/addonconfiguration/cma_progressing_reconciler_test.go
pkg/addon/controllers/addonmanagement/controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/client_builder.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go

- Address code review comments https://github.com/open-cluster-management-io/ocm/pull/728#discussion_r1863553376 (_test.go files did not change)
- Change kubecofnig secret creation time to non pointer to prevent [nil pointer panic](https://github.com/open-cluster-management-io/ocm/blob/6e367a2b26b7cf8fca83bd3861de3281ae0224b3/pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go#L314)
Fixes #

🌱 Change kubecofnig secret creation time to non pointer

---

solutions/argocd-agent/README.md

Add a solution doc for integration with the [Argo CD Agent](https://github.com/argoproj-labs/argocd-agent) project.
https://github.com/open-cluster-management-io/addon-contrib/pull/23

:book: Add Argo CD Agent integration solution

---

go.mod
pkg/registration/register/aws_irsa/aws_irsa.go
pkg/registration/register/aws_irsa/options.go
pkg/registration/register/common.go
pkg/registration/register/csr/csr.go
pkg/registration/register/csr/options.go
pkg/registration/spoke/registration/registration_test.go
pkg/registration/spoke/spokeagent.go

Creates registration option by driver type after bootstrap and disables addon controller for aws-irsa type of authentication.
Fixes #

:bug: Registration option for aws-irsa type of authentication

---

pkg/addon/controllers/addontemplate/controller.go
pkg/addon/templateagent/decorator.go
pkg/addon/templateagent/decorator_test.go
pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/values.go
test/e2e/addonmanagement_test.go

✨ Support configuring proxy for addons

---

deploy/cluster-manager/chart/cluster-manager/templates/_helpers.tpl
deploy/cluster-manager/chart/cluster-manager/templates/cluster_manager.yaml
deploy/cluster-manager/chart/cluster-manager/templates/operator.yaml
deploy/cluster-manager/chart/cluster-manager/values.yaml
deploy/klusterlet/chart/klusterlet/templates/_helpers.tpl
deploy/klusterlet/chart/klusterlet/templates/klusterlet.yaml
deploy/klusterlet/chart/klusterlet/templates/operator.yaml
deploy/klusterlet/chart/klusterlet/values.yaml

:sparkles: support override images in helm chart

---

deploy/cluster-manager/chart/cluster-manager/values.yaml
deploy/cluster-manager/config/operator/operator.yaml
deploy/cluster-manager/olm-catalog/latest/manifests/cluster-manager.clusterserviceversion.yaml

Remove the limit of cluster-manager for benefits (ref https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits):
- To avoid OOM
- Limits can cause issues on Large clusters 
Fixes #

:seedling: remove the resource limit for cluster-manager

---

solutions/joining-hub-and-spoke-with-aws-auth-manually/README.md

Making changes to step 9 in Manually join Hub and Spoke using AWS-based authentication document
Reference: https://github.com/open-cluster-management-io/ocm/issues/514

:book: Making changes to step 9 in Manually join Hub and Spoke using AWS-based authentication document

---

deploy/cluster-manager/chart/cluster-manager/templates/cluster_role.yaml
deploy/cluster-manager/config/rbac/cluster_role.yaml
deploy/cluster-manager/olm-catalog/latest/manifests/cluster-manager.clusterserviceversion.yaml
manifests/cluster-manager/hub/cluster-manager-registration-clusterrole.yaml

:bug: update rbac for capi

---

pkg/work/spoke/apply/update_apply.go
pkg/work/spoke/apply/update_apply_test.go

This could reduce the number of calls to the spoke cluster
Fixes #

🌱  Add cache for applyUnstructured

---

deploy/cluster-manager/chart/cluster-manager/templates/bootstrap_cluster_role.yaml
deploy/cluster-manager/chart/cluster-manager/templates/bootstrap_cluster_role_binding.yaml
deploy/cluster-manager/chart/cluster-manager/templates/bootstrap_sa.yaml
deploy/cluster-manager/chart/cluster-manager/templates/bootstrap_sa_cluster_role_binding.yaml
deploy/cluster-manager/chart/cluster-manager/templates/cluster_manager.yaml
deploy/cluster-manager/chart/cluster-manager/templates/cluster_role.yaml
deploy/cluster-manager/config/rbac/cluster_role.yaml
deploy/cluster-manager/olm-catalog/latest/manifests/cluster-manager.clusterserviceversion.yaml
manifests/cluster-manager/hub/cluster-manager-registration-clusterrole.yaml
pkg/registration/hub/importer/importer.go

:seedling: rename bootstrap sa and rbac

---

manifests/cluster-manager/management/cluster-manager-registration-deployment.yaml
manifests/config.go
pkg/operator/operators/clustermanager/controllers/clustermanagercontroller/clustermanager_controller.go
pkg/registration/hub/importer/importer.go
pkg/registration/hub/importer/options/options.go
pkg/registration/hub/importer/renderers.go
pkg/registration/hub/importer/renderers_test.go
pkg/registration/hub/manager.go
test/e2e/e2e_suite_test.go
test/framework/featuregate.go

🌱 Add bootstrapSA flags for importer

---

pkg/common/helpers/clusters.go
pkg/common/helpers/clusters_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_cleanup_controller_test.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_managed_reconcile.go
pkg/work/helper/helpers.go
pkg/work/spoke/controllers/finalizercontroller/appliedmanifestwork_finalize_controller.go
pkg/work/spoke/controllers/manifestcontroller/manifestwork_controller.go
pkg/work/spoke/controllers/statuscontroller/availablestatus_controller.go

:seedling: refactor to use common HasFinalizer func

---

go.mod
go.sum
test/integration/addon/addon_configs_test.go
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/addondeploymentconfig.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/addonconfig/controller.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/agentdeploy/healthcheck_sync.go
vendor/open-cluster-management.io/addon-framework/pkg/addonmanager/controllers/registration/controller.go
vendor/open-cluster-management.io/addon-framework/pkg/assets/template.go

https://github.com/open-cluster-management-io/addon-framework/pull/298

:seedling: upgrade addon-framework

---

go.mod
pkg/registration/hub/managedcluster/controller.go
pkg/registration/hub/managedcluster/controller_test.go
pkg/registration/hub/manager.go
pkg/registration/register/aws_irsa/aws_irsa.go
pkg/registration/register/common.go
pkg/registration/register/common_test.go
pkg/registration/register/csr/approver.go
pkg/registration/register/csr/approver_test.go
pkg/registration/register/csr/csr.go
pkg/registration/register/interface.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_add_finalizer_test.go
pkg/work/hub/controllers/manifestworkreplicasetcontroller/manifestworkreplicaset_finalizer_test.go

🌱 Refactor hub driver interface and remove approver

---

ADOPTERS.md

Add a list of ecosystem projects to the Adopters file.
Fixes # NA

:seedling: Add a list of ecosystem projects to the Adopters file

---

pkg/registration/register/aws_irsa/hub_driver.go
pkg/registration/register/aws_irsa/hub_driver_test.go
vendor/github.com/aws/aws-sdk-go-v2/aws/arn/arn.go
vendor/modules.txt

Changes to cleanup the IAM resources and access entries created for aws irsa when HubAcceptsClient is set to false.
Fixes #[514](https://github.com/open-cluster-management-io/ocm/issues/514)

✨ ✨ cleanup IAM resources for aws irsa

---

pkg/operator/helpers/chart/config.go
pkg/operator/helpers/chart/render_test.go

:bug: fix nodeSelector type in the helm chart config

---

solutions/setup-dev-environment/README.md
solutions/setup-dev-environment/local-up.sh

Made some fixes in the local set-up script

📖 Made some typo fixes in the setup script

---

pkg/work/spoke/apply/server_side_apply.go
pkg/work/spoke/controllers/finalizercontroller/add_finalizer_controller.go
pkg/work/spoke/controllers/finalizercontroller/appliedmanifestwork_finalize_controller.go
pkg/work/spoke/controllers/finalizercontroller/manifestwork_finalize_controller.go
pkg/work/spoke/controllers/finalizercontroller/unmanaged_appliedmanifestwork_controller.go
pkg/work/spoke/controllers/manifestcontroller/manifestwork_controller.go
pkg/work/spoke/controllers/statuscontroller/availablestatus_controller.go

low the some log level to reduce the log size in the debug model (v=4)
Fixes #

:seedling: reduce unnecessary log for agent

---

solutions/argocd-agent/README.md

docs: Misc fixes to Argo CD Agent solution doc.
Fixes NA

:book: docs: Misc fixes to Argo CD Agent solution doc

---

Makefile
hack/update-csv.sh

:seedling: update make update-csv

---

pkg/registration/spoke/addon/lease_controller.go
pkg/registration/spoke/addon/lease_controller_test.go
pkg/registration/spoke/spokeagent.go

⚠️ Remove checking leases on hub

---

pkg/common/helpers/event_recorder.go
pkg/common/helpers/event_recorder_test.go
pkg/placement/controllers/manager.go
pkg/registration/hub/lease/controller_test.go
pkg/registration/hub/manager.go
pkg/registration/register/aws_irsa/aws.go
pkg/registration/register/aws_irsa/aws_irsa.go
pkg/registration/register/common.go
pkg/registration/register/csr/csr.go
pkg/registration/spoke/lease/lease_controller.go
pkg/registration/spoke/lease/lease_controller_test.go
pkg/registration/spoke/managedcluster/claim_reconcile_test.go
pkg/registration/spoke/managedcluster/joining_controller_test.go
pkg/registration/spoke/managedcluster/resource_reconcile_test.go
pkg/registration/spoke/registration/hub_timeout_controller.go
pkg/registration/spoke/registration/hub_timeout_controller_test.go
pkg/registration/spoke/spokeagent.go

🌱 Reduce client scope built from driver

---

go.mod
go.sum
vendor/modules.txt
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/clients/store/base.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/clients/store/interface.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/clients/store/lister.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/clients/work/agent/client/manifestwork.go
vendor/open-cluster-management.io/sdk-go/pkg/cloudevents/clients/work/source/client/manifestwork.go

:seedling: upgrade go-sdk

---

deploy/klusterlet/chart/klusterlet/templates/agent-namespace.yaml
deploy/klusterlet/chart/klusterlet/templates/image_pull_secret.yaml
pkg/operator/helpers/chart/render_test.go

1. should create image pull secret if noOperator is true.
2. do not create agent namespace if Release.Namespace is the agent namespace.
Fixes #

:seedling:  update klusterlet helm chart

---

go.mod
go.sum
pkg/addon/controllers/addontemplate/controller.go
pkg/addon/controllers/addontemplate/controller_test.go
pkg/addon/templateagent/decorator.go
pkg/addon/templateagent/decorator_test.go
pkg/addon/templateagent/template_agent.go
pkg/addon/templateagent/values.go
test/e2e/addonmanagement_test.go
vendor/modules.txt
vendor/open-cluster-management.io/addon-framework/pkg/addonfactory/addondeploymentconfig.go
vendor/open-cluster-management.io/addon-framework/pkg/utils/probe_helper.go

✨ Support configuring resource requirements for addon agents

---

pkg/registration/register/aws_irsa/aws_irsa.go
pkg/registration/register/common.go
pkg/registration/register/csr/certificate.go
pkg/registration/register/csr/certificate_test.go
pkg/registration/register/csr/csr.go
pkg/registration/register/csr/csr_test.go
pkg/registration/register/factory/options.go
pkg/registration/spoke/health_checker_test.go
pkg/registration/spoke/options.go
pkg/registration/spoke/spokeagent.go
pkg/registration/spoke/spokeagent_test.go

1. make IsCertificateValid to public
2. check existence of bootstrap kubeconfig in the specific driver
3. initiate clients from driver using bootstrapCtx in bootstrap phase
Fixes #

🌱 More refactor on registration part

---

solutions/argocd-agent/README.md

docs: update argocd-agent solution install instructions
https://github.com/open-cluster-management-io/addon-contrib/pull/28 should be merged first.
Fixes #NA

:book: docs: update argocd-agent solution install instructions

---

pkg/registration/register/csr/csr.go

🐛 Only check bootstrapKubeConfig when signer is kubeClient

---

solutions/kueue-admission-check/setup-env.sh

:seedling:  update the multikueue setup script

---

deploy/cluster-manager/olm-catalog/latest/manifests/cluster-manager.clusterserviceversion.yaml
deploy/klusterlet/olm-catalog/latest/manifests/klusterlet.clusterserviceversion.yaml
go.mod
go.sum
manifests/cluster-manager/hub/0000_00_clusters.open-cluster-management.io_managedclusters.crd.yaml
vendor/modules.txt
vendor/open-cluster-management.io/api/cluster/v1/0000_00_clusters.open-cluster-management.io_managedclusters.crd.yaml
vendor/open-cluster-management.io/api/cluster/v1/types.go

🐛 Make hubAcceptsClient optional

---

README.md

docs: update OCM README for ALC to reference Argo CD
Ref https://github.com/open-cluster-management-io/ocm/issues/951

:book: docs: update OCM README for ALC to reference Argo CD

---

pkg/work/spoke/controllers/statuscontroller/availablestatus_controller.go

Instead of requeue all each resyncInterval, we requeue for each item separately with a jitter to avoud bursty request
Fixes #

🌱 Add jitter in requeue for status controller

---

deploy/cluster-manager/chart/cluster-manager/crds/0000_01_operator.open-cluster-management.io_clustermanagers.crd.yaml
deploy/cluster-manager/config/crds/0000_01_operator.open-cluster-management.io_clustermanagers.crd.yaml
deploy/cluster-manager/olm-catalog/latest/manifests/cluster-manager.clusterserviceversion.yaml
deploy/cluster-manager/olm-catalog/latest/manifests/operator.open-cluster-management.io_clustermanagers.yaml
deploy/klusterlet/olm-catalog/latest/manifests/klusterlet.clusterserviceversion.yaml
go.mod
go.sum
vendor/modules.txt
vendor/open-cluster-management.io/api/operator/v1/0000_01_operator.open-cluster-management.io_clustermanagers.crd.yaml
vendor/open-cluster-management.io/api/operator/v1/types_clustermanager.go
vendor/open-cluster-management.io/api/operator/v1/zz_generated.swagger_doc_generated.go

🐛 Rectify the aws driver name to awsirsa

---

deploy/klusterlet/chart/klusterlet/crds/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml
deploy/klusterlet/config/crds/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml
go.mod
go.sum
manifests/cluster-manager/hub/0000_00_work.open-cluster-management.io_manifestworkreplicasets.crd.yaml
manifests/klusterlet/management/klusterlet-agent-deployment.yaml
manifests/klusterlet/management/klusterlet-work-deployment.yaml
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller.go
pkg/operator/operators/klusterlet/controllers/klusterletcontroller/klusterlet_controller_test.go
test/e2e/addonmanagement_test.go
test/e2e/e2e_suite_test.go
test/framework/klusterlet.go
vendor/modules.txt
vendor/open-cluster-management.io/api/operator/v1/0000_00_operator.open-cluster-management.io_klusterlets.crd.yaml
vendor/open-cluster-management.io/api/operator/v1/types_klusterlet.go
vendor/open-cluster-management.io/api/operator/v1/zz_generated.deepcopy.go
vendor/open-cluster-management.io/api/operator/v1/zz_generated.swagger_doc_generated.go
vendor/open-cluster-management.io/api/work/v1alpha1/0000_00_work.open-cluster-management.io_manifestworkreplicasets.crd.yaml
vendor/open-cluster-management.io/api/work/v1alpha1/types_manifestworkreplicaset.go
vendor/open-cluster-management.io/api/work/v1alpha1/zz_generated.swagger_doc_generated.go

✨ make work status sync interval configurable

---

test/e2e/addonmanagement_test.go

:bug:  check works in the addon management e2e case

---

pkg/registration/hub/gc/controller.go
pkg/registration/hub/managedcluster/controller.go

should requeue when get a requeueError.
Fixes #

:bug:  fix no requeue when return requeueError
